extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:

exporters:
  awsxray:

service:
  telemetry:
    logs:
      level: debug
    metrics:
      level: detailed
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [awsxray]
    # metrics:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [prometheus]

  extensions: [health_check]