---
networking:
  us-east-1:
    short_region: "use1"
    vpc:
      id: "vpc-0deebfda73fc9a9b2"
      name: "wdpr-guest360-tgw-use1-load"
      cidr:
        - "10.171.150.0/23"
        - "10.255.0.0/16"
    subnets:
      non-routable:
        - id: "subnet-0fa39626fce8ff736"
          cidr: "10.255.0.0/18"
        - id: "subnet-0d257f72d2b5f94f3"
          cidr: "10.255.64.0/18"
        - id: "subnet-01e02e47de78d256d"
          cidr: "10.255.128.0/18"
      private:
        - id: "subnet-01555168b6ee7212d"
          cidr: "10.171.151.0/25"
        - id: "subnet-0b111026408f9e021"
          cidr: "10.171.150.128/25"
        - id: "subnet-0bb525b97a3b73d35"
          cidr: "10.171.150.0/25"
    endpoints:
      - id: "vpce-03901ed7939d4477e"
        service_name: "kms"
        type: "Interface"
      - id: "vpce-03d236b0bb7170203"
        service_name: "kinesis-streams"
        type: "Interface"
      - id: "vpce-0305407929c8272d1"
        service_name: "ssmmessages"
        type: "Interface"
      - id: "vpce-024a1c1cd6655ef9f"
        service_name: "logs"
        type: "Interface"
      - id: "vpce-038ef08afa38c2778"
        service_name: "ssm"
        type: "Interface"
      - id: "vpce-0eb086f08b4686856"
        service_name: "config"
        type: "Interface"
      - id: "vpce-02eb62f7ac2e51b6a"
        service_name: "events"
        type: "Interface"
      - id: "vpce-0df7f093c5d338c24"
        service_name: "sns"
        type: "Interface"
      - id: "vpce-08c773712fce0e283"
        service_name: "storagegateway"
        type: "Interface"
      - id: "vpce-01244ed468b14641a"
        service_name: "secretsmanager"
        type: "Interface"
      - id: "vpce-00142caeaebf1de39"
        service_name: "monitoring"
        type: "Interface"
      - id: "vpce-0800840393f96f4b7"
        service_name: "ecs-agent"
        type: "Interface"
      - id: "vpce-0b9a4a7992923cdec"
        service_name: "ecs-telemetry"
        type: "Interface"
      - id: "vpce-09459fe124382158d"
        service_name: "execute-api"
        type: "Interface"
      - id: "vpce-0d540f5b28edf5cf6"
        service_name: "sqs"
        type: "Interface"
      - id: "vpce-0cce3ef9529fb23cf"
        service_name: "dynamodb"
        type: "Gateway"
      - id: "vpce-0efba02e03a6e2bb3"
        service_name: "s3"
        type: "Gateway"
  us-west-2:
    short_region: "usw2"
    vpc:
      id: "vpc-042b71c1ac02f62c5"
      name: "wdpr-guest360-tgw-usw2-load"
      cidr:
        - "10.170.148.0/23"
        - "10.255.0.0/16"
    subnets:
      non-routable:
        - id: "subnet-04bc774ea0361701f"
          cidr: "10.255.0.0/18"
        - id: "subnet-0b579dbc393f4d357"
          cidr: "10.255.64.0/18"
        - id: "subnet-01cbb9ba0cbfd10e5"
          cidr: "10.255.128.0/18"
      private:
        - id: "subnet-04a4a2c3bc659ae1f"
          cidr: "10.170.148.0/25"
        - id: "subnet-05649c072bdc9ea94"
          cidr: "10.170.149.0/25"
        - id: "subnet-007ad5d6cb421f9c1"
          cidr: "10.170.148.128/25"
    endpoints:
      - id: "vpce-0c5226d10af78dbcd"
        service_name: "events"
        type: "Interface"
      - id: "vpce-06d0d1b5f2344f562"
        service_name: "execute-api"
        type: "Interface"
      - id: "vpce-0703623d5db4e1a96"
        service_name: "logs"
        type: "Interface"
      - id: "vpce-070cf4184036e1cf9"
        service_name: "monitoring"
        type: "Interface"
      - id: "vpce-0d85347541d14f71a"
        service_name: "ecs-telemetry"
        type: "Interface"
      - id: "vpce-0ace673a5e3cb9423"
        service_name: "ssmmessages"
        type: "Interface"
      - id: "vpce-03584c539b9b11245"
        service_name: "secretsmanager"
        type: "Interface"
      - id: "vpce-0bdce3a08e0cb1a4f"
        service_name: "kinesis-streams"
        type: "Interface"
      - id: "vpce-0248bc5a6b67b7fea"
        service_name: "config"
        type: "Interface"
      - id: "vpce-0a1a4f2ebc7c8ea61"
        service_name: "ssm"
        type: "Interface"
      - id: "vpce-0433fdc51a37d9469"
        service_name: "sqs"
        type: "Interface"
      - id: "vpce-0943e2e8387a5b00b"
        service_name: "kms"
        type: "Interface"
      - id: "vpce-0e6734a9b2e3459e8"
        service_name: "sns"
        type: "Interface"
      - id: "vpce-0b65c8ed58069a75e"
        service_name: "ecs-agent"
        type: "Interface"
      - id: "vpce-0f2204f70f8ab15e8"
        service_name: "storagegateway"
        type: "Interface"
      - id: "vpce-0ca9e53dee6ad0931"
        service_name: "dynamodb"
        type: "Gateway"
      - id: "vpce-04ba1724398f83b85"
        service_name: "s3"
        type: "Gateway"
short_env: "lod"
...