---
networking:
  us-east-1:
    short_region: "use1"
    vpc:
      id: "vpc-0c0a061c77c82e8e9"
      name: "wdpr-guest360-tgw-use1-prod"
      cidr:
        - "10.171.166.0/23"
        - "10.255.0.0/16"
    subnets:
      non-routable:
        - id: "subnet-0de74aad8aa895879"
          cidr: "10.255.0.0/18"
        - id: "subnet-02621370a849f6e0d"
          cidr: "10.255.64.0/18"
        - id: "subnet-0cec373babbe48503"
          cidr: "10.255.128.0/18"
      private:
        - id: "subnet-05fc3e033b604c797"
          cidr: "10.171.166.0/25"
        - id: "subnet-0c830377ad8cd473d"
          cidr: "10.171.167.0/25"
        - id: "subnet-054aa81309c1a57a5"
          cidr: "10.171.166.128/25"
    endpoints:
      - id: "vpce-0fd0621698217a34e"
        service_name: "secretsmanager"
        type: "Interface"
      - id: "vpce-084e3e368cce9c174"
        service_name: "sqs"
        type: "Interface"
      - id: "vpce-021a311d8f83b3b00"
        service_name: "sns"
        type: "Interface"
      - id: "vpce-0dd89d31f37998386"
        service_name: "kinesis-streams"
        type: "Interface"
      - id: "vpce-0d9806d8b62297ebf"
        service_name: "kms"
        type: "Interface"
      - id: "vpce-05eaf05b6a9bff274"
        service_name: "storagegateway"
        type: "Interface"
      - id: "vpce-0f240851916486fc8"
        service_name: "execute-api"
        type: "Interface"
      - id: "vpce-0a2f2c31a208a1de8"
        service_name: "events"
        type: "Interface"
      - id: "vpce-0d905b18c0301da1c"
        service_name: "ssm"
        type: "Interface"
      - id: "vpce-07dcce2c941543a70"
        service_name: "logs"
        type: "Interface"
      - id: "vpce-0cb108f8acf620934"
        service_name: "ssmmessages"
        type: "Interface"
      - id: "vpce-083317216b0636b2b"
        service_name: "monitoring"
        type: "Interface"
      - id: "vpce-0ae5af0e423016495"
        service_name: "ecs-telemetry"
        type: "Interface"
      - id: "vpce-0e74edb66cebdff9c"
        service_name: "config"
        type: "Interface"
      - id: "vpce-03a14494d4506b5f9"
        service_name: "ecs-agent"
        type: "Interface"
      - id: "vpce-0a27a182a034e97cb"
        service_name: "dynamodb"
        type: "Gateway"
      - id: "vpce-0644894651ecb5895"
        service_name: "s3"
        type: "Gateway"
  us-west-2:
    short_region: "usw2"
    vpc:
      id: "vpc-06b3e3d27613283cd"
      name: "wdpr-guest360-tgw-usw2-prod"
      cidr:
        - "10.170.152.0/23"
        - "10.255.0.0/16"
    subnets:
      non-routable:
        - id: "subnet-03ba549dd58503b92"
          cidr: "10.255.0.0/18"
        - id: "subnet-0b20e836eae105da9"
          cidr: "10.255.64.0/18"
        - id: "subnet-077999f75247d7436"
          cidr: "10.255.128.0/18"
      private:
        - id: "subnet-0492977fe10cc52ab"
          cidr: "10.170.152.128/25"
        - id: "subnet-0d63b6514b987bdc1"
          cidr: "10.170.152.0/25"
        - id: "subnet-04ebc5bb147ea73ad"
          cidr: "10.170.153.0/25"
    endpoints:
      - id: "vpce-08f03e35c72930f35"
        service_name: "kinesis-streams"
        type: "Interface"
      - id: "vpce-0688ced766c10eb40"
        service_name: "sqs"
        type: "Interface"
      - id: "vpce-0bcd10fac818d2073"
        service_name: "logs"
        type: "Interface"
      - id: "vpce-0789ac1383a000d2a"
        service_name: "storagegateway"
        type: "Interface"
      - id: "vpce-05947f4102e22a9d2"
        service_name: "ssmmessages"
        type: "Interface"
      - id: "vpce-03d71bbf44b4ab9c7"
        service_name: "ssm"
        type: "Interface"
      - id: "vpce-0cdf2adf54ea8d4a0"
        service_name: "config"
        type: "Interface"
      - id: "vpce-0f6a8fe777631d1c7"
        service_name: "execute-api"
        type: "Interface"
      - id: "vpce-08282ca8dd2662043"
        service_name: "secretsmanager"
        type: "Interface"
      - id: "vpce-0578d176094faa3c5"
        service_name: "sns"
        type: "Interface"
      - id: "vpce-0ade21aeac7686e85"
        service_name: "monitoring"
        type: "Interface"
      - id: "vpce-00da1f99f7b2d1c1e"
        service_name: "ecs-agent"
        type: "Interface"
      - id: "vpce-01ff1f9de1ecfeed6"
        service_name: "kms"
        type: "Interface"
      - id: "vpce-0bd50229e4276f32e"
        service_name: "ecs-telemetry"
        type: "Interface"
      - id: "vpce-0367a72efe080deb5"
        service_name: "events"
        type: "Interface"
      - id: "vpce-0b0d5d1a1b590aad9"
        service_name: "dynamodb"
        type: "Gateway"
      - id: "vpce-08d01a698da03de70"
        service_name: "s3"
        type: "Gateway"
short_env: "prd"
...