---
account: "863175788676"
networking:
  us-east-1:
    short_region: "use1"
    vpc:
      id: "vpc-0d29f1e134f1fe44e"
      name: "wdpr-guest360-tgw-use1-stage"
      cidr:
        - "10.171.136.0/23"
        - "10.255.0.0/16"
    subnets:
      non-routable:
        - id: "subnet-0699cedc02ef9f243"
          cidr: "10.255.0.0/18"
        - id: "subnet-03da9c4217e410279"
          cidr: "10.255.64.0/18"
        - id: "subnet-06d4f6da0a88af6d9"
          cidr: "10.255.128.0/18"
      private:
        - id: "subnet-0218afd65dd0c48b9"
          cidr: "10.171.136.128/25"
        - id: "subnet-0af5c3a3af5979ba9"
          cidr: "10.171.137.0/25"
        - id: "subnet-0fec52d55fb86b4e2"
          cidr: "10.171.136.0/25"
    resolvers:
      foo:
        - SubnetId: subnet-0218afd65dd0c48b9
          Ip: 10.171.136.129
      foo1:
        - SubnetId: subnet-0218afd65dd0c48b9
          ip: 10.171.136.129
    endpoints:
      - id: "vpce-0f9c26a76721befa4"
        service_name: "kinesis-streams"
        type: "Interface"
      - id: "vpce-07cabd8e9e4c8097e"
        service_name: "ecs-telemetry"
        type: "Interface"
      - id: "vpce-028159135487e3ba6"
        service_name: "ssm"
        type: "Interface"
      - id: "vpce-06c9e42a9595d16da"
        service_name: "execute-api"
        type: "Interface"
      - id: "vpce-07a2a3a9ea3a2597f"
        service_name: "kms"
        type: "Interface"
      - id: "vpce-0db2a94057cd45bb0"
        service_name: "events"
        type: "Interface"
      - id: "vpce-03968af95ca508b80"
        service_name: "ssmmessages"
        type: "Interface"
      - id: "vpce-02ee869a620355e7e"
        service_name: "logs"
        type: "Interface"
      - id: "vpce-032619297aed38ddc"
        service_name: "secretsmanager"
        type: "Interface"
      - id: "vpce-023783e300492716a"
        service_name: "monitoring"
        type: "Interface"
      - id: "vpce-06475f2d86b631816"
        service_name: "sns"
        type: "Interface"
      - id: "vpce-0d16376bc3c007bb2"
        service_name: "ecs-agent"
        type: "Interface"
      - id: "vpce-097fe7af4a19463c9"
        service_name: "config"
        type: "Interface"
      - id: "vpce-0ac72c33c753dbbab"
        service_name: "sqs"
        type: "Interface"
      - id: "vpce-0b83c80d58c862983"
        service_name: "storagegateway"
        type: "Interface"
      - id: "vpce-0ed27d8ae1302d070"
        service_name: "dynamodb"
        type: "Gateway"
      - id: "vpce-0838bfbd6a83b72d7"
        service_name: "s3"
        type: "Gateway"
  us-west-2:
    short_region: "usw2"
    vpc:
      id: "vpc-0a10f6e58c781f3e0"
      name: "wdpr-guest360-tgw-usw2-stage"
      cidr:
        - "10.170.140.0/23"
        - "10.255.0.0/16"
    subnets:
      non-routable:
        - id: "subnet-080dad27dba513a6e"
          cidr: "10.255.0.0/18"
        - id: "subnet-0fdb6b46c05ca4ed5"
          cidr: "10.255.64.0/18"
        - id: "subnet-053c750e5743813c0"
          cidr: "10.255.128.0/18"
      private:
        - id: "subnet-02d520013e284eee8"
          cidr: "10.170.141.0/25"
        - id: "subnet-03239ffd73d65c1c5"
          cidr: "10.170.140.128/25"
        - id: "subnet-0f5bce9ee667336c4"
          cidr: "10.170.140.0/25"
    endpoints:
      - id: "vpce-06de941f5a4ae895d"
        service_name: "ssm"
        type: "Interface"
      - id: "vpce-0b4aa651b722dcc4b"
        service_name: "storagegateway"
        type: "Interface"
      - id: "vpce-0a259ede806b011e2"
        service_name: "execute-api"
        type: "Interface"
      - id: "vpce-0cddafab75ae65e2b"
        service_name: "events"
        type: "Interface"
      - id: "vpce-0d71abe6a5ea877f7"
        service_name: "logs"
        type: "Interface"
      - id: "vpce-01d066cd0bbd18254"
        service_name: "secretsmanager"
        type: "Interface"
      - id: "vpce-0dfe9206368973e29"
        service_name: "ecs-telemetry"
        type: "Interface"
      - id: "vpce-0470bddb7ffb79705"
        service_name: "config"
        type: "Interface"
      - id: "vpce-0841094adfb281cb1"
        service_name: "sns"
        type: "Interface"
      - id: "vpce-0bba54ab896e2083f"
        service_name: "sqs"
        type: "Interface"
      - id: "vpce-045692296fb24cdcc"
        service_name: "monitoring"
        type: "Interface"
      - id: "vpce-07d2b086f28dcfa57"
        service_name: "ecs-agent"
        type: "Interface"
      - id: "vpce-07cfaa6c4caa701d2"
        service_name: "kinesis-streams"
        type: "Interface"
      - id: "vpce-086cc8d20b2bc6ddb"
        service_name: "kms"
        type: "Interface"
      - id: "vpce-0c7491f8f6e932089"
        service_name: "ssmmessages"
        type: "Interface"
      - id: "vpce-08d38ba220237b267"
        service_name: "s3"
        type: "Gateway"
      - id: "vpce-09c64e6dc13550d1f"
        service_name: "dynamodb"
        type: "Gateway"
short_env: "stg"
...