---
account: "543276908693"
networking:
  us-east-1:
    short_region: "use1"
    vpc:
      id: "vpc-02da7a04db8bee27b"
      name: "wdpr-guest360-tgw-use1-latest"
      cidr:
        - "10.171.98.0/23"
        - "10.255.0.0/16"
    subnets:
      non-routable:
        - id: "subnet-046334753c76ec831"
          cidr: "10.255.128.0/18"
        - id: "subnet-0a11990d33b5eda4a"
          cidr: "10.255.64.0/18"
        - id: "subnet-08d5a302e1e279ef4"
          cidr: "10.255.0.0/18"
      private:
        - id: "subnet-03826471aa279ce09"
          cidr: "10.171.98.0/25"
        - id: "subnet-007603f42a31101b1"
          cidr: "10.171.99.0/25"
        - id: "subnet-0a28c8fdd2b6b3bdf"
          cidr: "10.171.98.128/25"
    resolvers:
      foo:
        - Ip: subnet-03826471aa279ce09
          SubnetId: 10.171.98.2
        - Ip: subnet-007603f42a31101b1
          SubnetId: 10.171.99.2
      foo1:
        - ip: subnet-03826471aa279ce09
          SubnetId: 10.171.98.2
    endpoints:
      - id: "vpce-08900cd41ebaa4322"
        service_name: "events"
        type: "Interface"
      - id: "vpce-0443a18369121d5dd"
        service_name: "ssmmessages"
        type: "Interface"
      - id: "vpce-05f2def6cc7aaf5d7"
        service_name: "sns"
        type: "Interface"
      - id: "vpce-0081be8a6c5e738e3"
        service_name: "execute-api"
        type: "Interface"
      - id: "vpce-0530e9dbd6f9c6f48"
        service_name: "storagegateway"
        type: "Interface"
      - id: "vpce-04ccc3cd366b371f6"
        service_name: "ecs-agent"
        type: "Interface"
      - id: "vpce-0b0a30559ca959ca5"
        service_name: "logs"
        type: "Interface"
      - id: "vpce-0b1e682aa7000f05f"
        service_name: "secretsmanager"
        type: "Interface"
      - id: "vpce-004ca223db0a1881d"
        service_name: "ssm"
        type: "Interface"
      - id: "vpce-01847de247d31d7a0"
        service_name: "config"
        type: "Interface"
      - id: "vpce-0f9d13065cf450f64"
        service_name: "monitoring"
        type: "Interface"
      - id: "vpce-067963cf3eb33afc6"
        service_name: "kms"
        type: "Interface"
      - id: "vpce-000fc709101428509"
        service_name: "kinesis-streams"
        type: "Interface"
      - id: "vpce-0952748d9f40c09f0"
        service_name: "sqs"
        type: "Interface"
      - id: "vpce-01e7c8966fac21c1f"
        service_name: "ecs-telemetry"
        type: "Interface"
      - id: "vpce-095f0d512b2c95b31"
        service_name: "s3"
        type: "Gateway"
      - id: "vpce-0a9d22f25e8721b25"
        service_name: "dynamodb"
        type: "Gateway"
  us-west-2:
    short_region: "usw2"
    vpc:
      id: "vpc-0949d89a5d8a0fe0a"
      name: "wdpr-guest360-tgw-usw2-latest"
      cidr:
        - "10.170.94.0/23"
        - "10.255.0.0/16"
    subnets:
      non-routable:
        - id: "subnet-099f68682cc711d2d"
          cidr: "10.255.0.0/18"
        - id: "subnet-0a3ceb498c25769c7"
          cidr: "10.255.64.0/18"
        - id: "subnet-025ef3cff863cfe91"
          cidr: "10.255.128.0/18"
      private:
        - id: "subnet-0bd8aa52a26f5221b"
          cidr: "10.170.94.0/25"
        - id: "subnet-0328b90f3efe0c2c4"
          cidr: "10.170.94.128/25"
        - id: "subnet-0925ad3394cb0a615"
          cidr: "10.170.95.0/25"
    endpoints:
      - id: "vpce-0b27a45dd42469713"
        service_name: "ssm"
        type: "Interface"
      - id: "vpce-01d824c8c84e81d8b"
        service_name: "secretsmanager"
        type: "Interface"
      - id: "vpce-0c756751273db2252"
        service_name: "sqs"
        type: "Interface"
      - id: "vpce-0b85cf673f9a2ed86"
        service_name: "monitoring"
        type: "Interface"
      - id: "vpce-0e35bb224df9ee076"
        service_name: "kms"
        type: "Interface"
      - id: "vpce-0d383510aa65ff999"
        service_name: "sns"
        type: "Interface"
      - id: "vpce-0525d4d604dde68d2"
        service_name: "ssmmessages"
        type: "Interface"
      - id: "vpce-06c07a14027277a82"
        service_name: "execute-api"
        type: "Interface"
      - id: "vpce-03fe15cdd7136f570"
        service_name: "ecs-agent"
        type: "Interface"
      - id: "vpce-0cba8560fffcd261a"
        service_name: "ecs-telemetry"
        type: "Interface"
      - id: "vpce-0fea417d111885d7e"
        service_name: "config"
        type: "Interface"
      - id: "vpce-097a1c42728826ba7"
        service_name: "events"
        type: "Interface"
      - id: "vpce-01185ef6fdf8ac2d4"
        service_name: "kinesis-streams"
        type: "Interface"
      - id: "vpce-04f59e372b263826e"
        service_name: "storagegateway"
        type: "Interface"
      - id: "vpce-0cd1150594a16aae5"
        service_name: "logs"
        type: "Interface"
      - id: "vpce-087aa4e77e58fc860"
        service_name: "s3"
        type: "Gateway"
      - id: "vpce-0ba5d079ef5a6da24"
        service_name: "dynamodb"
        type: "Gateway"
short_env: "lst"
...