version: 2

models:
  - name: sil__intermediate__xbms__wdw__cost_ctr_config_cleansed
    description: '{{ doc("sil__intermediate__xbms__wdw__cost_ctr_config_cleansed") }}'

    meta:
      environment_wh:
        - env: LOCAL
          wh: GUEST_EXPERIENCE_LATEST_WH_S
        - env: LATEST
          wh: GUEST_EXPERIENCE_LATEST_WH_S
        - env: EPHEMERAL_PR
          wh: PR_SMALL_WH
        - env: STAGE
          wh: GUEST_EXPERIENCE_STAGE_WH_M
        - env: PROD
          wh: GUEST_EXPERIENCE_PROD_WH_M

    config:
      tags:
        - layer=silver_intermediate
        - sub_layer=silver_intermediate_cleansed
        - active=LATEST
        - active=STAGE
        - active=LOAD
        - active=PROD

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - data_cost_ctr_config_id
            - metadata_checksum

    columns:
      - name: data_cost_ctr_config_id
        description: ""
        tags: ['column_designation=primary_key']
        tests:
          - not_null

      - name: data_txn_src_sys_tx
        description: ""
        meta:
          checksum: True

      - name: data_dsny_fac_id
        description: ""
        meta:
          checksum: True

      - name: data_cntry_id
        description: ""
        meta:
          checksum: True

      - name: data_ship_insd_fl
        description: ""
        meta:
          checksum: True

      - name: data_ship_outsd_fl
        description: ""
        meta:
          checksum: True

      - name: data_cost_ctr_id
        description: ""
        meta:
          checksum: True

      - name: data_wbs_elmnt_id
        description: ""
        meta:
          checksum: True

      - name: data_gnrl_ldgr_id
        description: ""
        meta:
          checksum: True

      - name: data_create_usr_id
        description: ""
        meta:
          checksum: True

      - name: data_create_dts
        description: ""
        meta:
          checksum: True

      - name: data_updt_usr_id
        description: ""
        meta:
          checksum: True

      - name: data_updt_dts
        description: ""

      - name: data_logical_del_in
        description: ""
        meta:
          checksum: True

      - name: min_metadata_timestamp
        description: "The Minimum Metadata Timestamp field is used for updating the version end date of the active record in the target table"
        tests:
          - not_null

      - name: metadata_checksum
        description: "Metadata Checksum"
        tests:
          - not_null

      - name: metadata_timestamp
        description: "Timestamp of when the record was sent to the stream | example: 2023-08-11 14:38:01.378618"
        tests:
          - not_null

      - name: metadata_record_type
        description: "Type of record | example: data"

      - name: metadata_operation
        description: "Type of operation [insert, delete, update] | example: update"

      - name: metadata_partition_key_type
        description: "Partition key | example: schema-table"

      - name: metadata_schema_name
        description: "Name of schema | example: SFLNSMD"

      - name: metadata_table_name
        description: "Name of table | example: AP_LVL_N_ENTTL_FISCAL_DT"

      - name: metadata_transaction_id
        description: "Unique Transaction Identifier | example: 59558768559209"

      - name: metadata_transaction_record_id
        description: "Transaction Record ID | example: 70974432245344"

      - name: metadata_prev_transaction_id
        description: "Previous Transaction ID | example: 70974432245344"

      - name: metadata_prev_transaction_record_id
        description: "Previous Transaction Record ID | example: 70974432245344"

      - name: metadata_commit_timestamp
        description: "Commit Timestamp | example: 2023-03-29T15:30:19.109655Z"

      - name: metadata_stream_position
        description: "Stream Position | example:"

      - name: metadata_insert_datetime
        description: "This is the current timestamp in UTC when the record is inserted"
        tests:
          - not_null

      - name: metadata_batch_user
        description: "Batch user. Default value will be dbt"
        tests:
          - not_null

      - name: landing_id
        description: ""

      - name: landing_file_name
        description: ""

      - name: landing_file_row_number
        description: ""

      - name: landing_file_last_modified
        description: ""

      - name: landing_timestamp
        description: ""

      - name: landing_cloudevent_id
        description: ""

      - name: landing_cloudevent_specversion
        description: ""

      - name: landing_cloudevent_time
        description: ""

      - name: landing_cloudevent_source
        description: ""

      - name: landing_cloudevent_subject
        description: ""

      - name: landing_cloudevent_stream
        description: ""

      - name: landing_cloudevent_type
        description: ""

      - name: landing_cloudevent_dataschema
        description: ""

      - name: landing_cloudevent_traceparent
        description: ""

      - name: landing_cloudevent_tracestate
        description: ""

      - name: landing_cloudevent_check_sum
        description: ""

      - name: landing_cloudevent_router_database
        description: ""

      - name: landing_cloudevent_router_schema
        description: ""

      - name: landing_cloudevent_router_table
        description: ""

      - name: landing_cloudevent_validated
        description: ""

      - name: landing_cloudevent_data_contract_version
        description: ""

      - name: landing_cloudevent_datacontenttype
        description: ""

      - name: landing_cloudevent_exception_error
        description: ""