"""Source Data Contract for GAM WDW Guest ID Keyring"""
from __future__ import annotations
from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field


class GuestIdentifierItem(BaseModel):
    """Data class that represents the Guest ID Type/Value pairs"""

    type: str = Field(
        ...,
        alias="type",
        name="Guest Identifier Type",
        description="Guest identifier type - SWID, GUID etc.",
        example="swid",
        guest_identifier=False,
        transaction_identifier=False,
        identifier_tag="",
    )
    value: str = Field(
        ...,
        alias="value",
        name="Guest Identifier Value",
        description="Guest identifier value corresponding to the Guest ID type",
        example="{A1A1A1A1-A1A1-A1A1-A1A1-A1A1A1A1A1A1}",
        guest_identifier=True,
        transaction_identifier=False,
        identifier_tag="Indirect",
    )


class GAMWDWGuestIdModel(BaseModel):
    """Payload class for GAMWDWGuestIdModel"""

    class Config:
        """Payload Level Metadata"""

        title = "GAM DLR Guest ID"
        stream_name = "gam-kinesis-gk-guestid-guest360-wdw"
        description = "WDW Guest IDs linked via a common xID in GAM"  # optional
        unique_identifier = []
        timezone = "UTC"  # optional
        pi_category = [""]  # optional
        isps = "Internal Use"  # optional
        financial_data = False  # optional
        version = "0.0.1"
        key_path_name = "type"  # optional
        key_path_value = "GuestId"  # optional

    action: str = Field(
        ...,
        alias="action",
        name="Event Action",
        description="Describes whether the Guest Identifier was newly added (assigned new xid), or merged (re-assigned xid), or removed from GAM",
        example="ADD",
        guest_identifier=False,
        transaction_identifier=False,
        identifier_tag="",
    )
    type: str = Field(
        ...,
        alias="type",
        name="Event Type",
        description="Represents the GAM event name - always GUESTID",
        example="GUESTID",
        guest_identifier=False,
        transaction_identifier=False,
        identifier_tag="",
    )
    correlation_id: str = Field(
        ...,
        alias="correlationId",
        name="Correlation ID from source systems",
        description="CorrelationId, as received from the source system (not created by GAM)",
        example="SYS-385268196526-4001986-2060331-1422274",
        guest_identifier=False,
        transaction_identifier=False,
        identifier_tag="",
    )
    added_guest_identifiers: Optional[List[GuestIdentifierItem]] = Field(
        None,
        alias="addedGuestIdentifiers",
        name="Added Guest Identifier Type/Value pairs",
        description="Often just one Guest Identifier type/value pair that is newly added into GAM",
    )
    previous_guest_identifiers: Optional[List[GuestIdentifierItem]] = Field(
        None,
        alias="previousGuestIdentifiers",
        name="Guest Identifier Type/Value pairs before an ADD or REMOVE action",
        description="Represents the existing group that the newly added type/value pair is merging into, or type/value pair is removed from",
    )
    resulting_guest_identifiers: List[GuestIdentifierItem] = Field(
        ...,
        alias="resultingGuestIdentifiers",
        name="Resulting Guest Identifier Type/Value pairs",
        description="Final representation of the group following the ADD/MERGE/REMOVE action",
    )
    removed_guest_identifiers: Optional[List[GuestIdentifierItem]] = Field(
        None,
        alias="removedGuestIdentifiers",
        name="Removed Guest Idenfitier Type/Value pairs",
        description="Often just one Guest Identifier type/value pair that is being removed from GAM",
    )
    previous_guest_identifiers1: Optional[List[GuestIdentifierItem]] = Field(
        None,
        alias="previousGuestIdentifiers1",
        name="Set1 of merging Guest Identifier Type/Value pairs",
        description="Guest Identifier type/value pair(s) that merges with another group",
    )
    previous_guest_identifiers2: Optional[List[GuestIdentifierItem]] = Field(
        None,
        alias="previousGuestIdentifiers2",
        name="Set2 of merging Guest Identifier Type/Value pairs",
        description="Represents an existing group that the type/value pair from set1 is merging into, leaving its previous xid",
    )
    timestamp: datetime = Field(
        ...,
        alias="timestamp",
        name="Event timestamp",
        description="Timestamp of the event generated by GAM",
        example="2023-03-29T12:57:49Z",
        guest_identifier=False,
        transaction_identifier=False,
        identifier_tag="",
    )
