stack_extension: &se dreams-resm
ingest_pattern: kinesis2kinesis
active: True
pattern_instances:
  - region: us-east-1
    resources:
      cross_account:
        cross_account_type: &cat target
        cross_account_id: &id 536797260050 
        cross_account_role_name: lllingest-use1-stg-lllingest-lambda
