stack_extension: &se virtualqueue-dlr
ingest_pattern: kinesis2kinesis
active: true
pattern_instances:
  - region: us-east-1
    resources:
      cross_account:
        cross_account_type: &cat target
        cross_account_id: &id 881472257814
        cross_account_role_name: dlr-fastpass-S0001537-usw2-stg_role
    data_pipe:
      default_router_database: DEFAULT_ROUTER_STAGE_LANDING # Needs update to appropriate default routing
      default_schema: &schema LND_VIRTUALQUEUE_DLR
      table_path: _type # This should match key_path_name
      data_contracts:
        - data_contract: app.src.data_structures.data_contracts.source.virtualqueue_dlr.v0.virtualqueue_dlr_boarding_group_created_event_source_data_contract
          class_name: VirtualQueueDLRBoardingGroupCreatedEventModel
          data_contract_version: 0.0.1
          key_path:
            - name: _type
              value: BoardingGroupCreatedEvent
          router_database: &database STAGE_LANDING
          router_schema: *schema
          router_table: BOARDING_GROUP_CREATED_EVENT
        - data_contract: app.src.data_structures.data_contracts.source.virtualqueue_dlr.v0.virtualqueue_dlr_boarding_group_released_event_source_data_contract
          class_name: VirtualQueueDLRBoardingGroupReleasedEventModel
          data_contract_version: 0.0.1
          key_path:
            - name: _type
              value: BoardingGroupReleasedEvent
          router_database: *database
          router_schema: *schema
          router_table: BOARDING_GROUP_RELEASED_EVENT
        - data_contract: app.src.data_structures.data_contracts.source.virtualqueue_dlr.v0.virtualqueue_dlr_boarding_group_summoned_event_source_data_contract
          class_name: VirtualQueueDLRBoardingGroupSummonedEventModel
          data_contract_version: 0.0.1
          key_path:
            - name: _type
              value: BoardingGroupSummonedEvent
          router_database: *database
          router_schema: *schema
          router_table: BOARDING_GROUP_SUMMONED_EVENT
        - data_contract: app.src.data_structures.data_contracts.source.virtualqueue_dlr.v0.virtualqueue_dlr_join_boarding_group_queue_event_source_data_contract
          class_name: VirtualQueueDLRJoinBoardingGroupQueueEventModel
          data_contract_version: 0.0.1
          key_path:
            - name: _type
              value: JoinBoardingGroupQueueEvent
          router_database: *database
          router_schema: *schema
          router_table: JOIN_BOARDING_GROUP_QUEUE_EVENT
        - data_contract: app.src.data_structures.data_contracts.source.virtualqueue_dlr.v0.virtualqueue_dlr_leave_boarding_group_queue_event_source_data_contract
          class_name: VirtualQueueDLRLeaveBoardingGroupQueueEventModel
          data_contract_version: 0.0.1
          key_path:
            - name: _type
              value: LeaveBoardingGroupQueueEvent
          router_database: *database
          router_schema: *schema
          router_table: LEAVE_BOARDING_GROUP_QUEUE_EVENT
        - data_contract: app.src.data_structures.data_contracts.source.virtualqueue_dlr.v0.virtualqueue_dlr_mobile_join_boarding_group_queue_event_source_data_contract
          class_name: VirtualQueueDLRMobileJoinBoardingGroupQueueEventModel
          data_contract_version: 0.0.1
          key_path:
            - name: _type
              value: MobileJoinBoardingGroupQueueEvent
          router_database: *database
          router_schema: *schema
          router_table: MOBILE_JOIN_BOARDING_GROUP_QUEUE_EVENT
        - data_contract: app.src.data_structures.data_contracts.source.virtualqueue_dlr.v0.virtualqueue_dlr_mobile_leave_queue_event_source_data_contract
          class_name: VirtualQueueDLRMobileLeaveQueueEventModel
          data_contract_version: 0.0.1
          key_path:
            - name: _type
              value: MobileLeaveQueueEvent
          router_database: *database
          router_schema: *schema
          router_table: MOBILE_LEAVE_QUEUE_EVENT
        - data_contract: app.src.data_structures.data_contracts.source.virtualqueue_dlr.v0.virtualqueue_dlr_queue_autosummon_snoozed_event_source_data_contract
          class_name: VirtualQueueDLRQueueAutosummonSnoozedEventModel
          data_contract_version: 0.0.1
          key_path:
            - name: _type
              value: QueueAutosummonSnoozedEvent
          router_database: *database
          router_schema: *schema
          router_table: QUEUE_AUTOSUMMON_SNOOZED_EVENT
        - data_contract: app.src.data_structures.data_contracts.source.virtualqueue_dlr.v0.virtualqueue_dlr_queue_config_modified_event_source_data_contract
          class_name: VirtualQueueDLRQueueConfigModifiedEventModel
          data_contract_version: 0.0.1
          key_path:
            - name: _type
              value: QueueConfigModifiedEvent
          router_database: *database
          router_schema: *schema
          router_table: QUEUE_CONFIG_MODIFIED_EVENT
        - data_contract: app.src.data_structures.data_contracts.source.virtualqueue_dlr.v0.virtualqueue_dlr_queue_emptied_event_source_data_contract
          class_name: VirtualQueueDLRQueueEmptiedEventModel
          data_contract_version: 0.0.1
          key_path:
            - name: _type
              value: QueueEmptiedEvent
          router_database: *database
          router_schema: *schema
          router_table: QUEUE_EMPTIED_EVENT
        - data_contract: app.src.data_structures.data_contracts.source.virtualqueue_dlr.v0.virtualqueue_dlr_queue_is_autosummon_enabled_updated_event_source_data_contract
          class_name: VirtualQueueDLRQueueIsAutosummonEnabledUpdatedEventModel
          data_contract_version: 0.0.1
          key_path:
            - name: _type
              value: QueueIsAutosummonEnabledUpdatedEvent
          router_database: *database
          router_schema: *schema
          router_table: QUEUE_IS_AUTOSUMMON_ENABLED_UPDATED_EVENT
        - data_contract: app.src.data_structures.data_contracts.source.virtualqueue_dlr.v0.virtualqueue_dlr_redemption_join_boarding_group_queue_event_source_data_contract
          class_name: VirtualQueueDLRRedemptionJoinBoardingGroupQueueEventModel
          data_contract_version: 0.0.1
          key_path:
            - name: _type
              value: RedemptionJoinBoardingGroupQueueEvent
          router_database: *database
          router_schema: *schema
          router_table: REDEMPTION_JOIN_BOARDING_GROUP_QUEUE_EVENT
        - data_contract: app.src.data_structures.data_contracts.source.virtualqueue_dlr.v0.virtualqueue_dlr_redemption_leave_queue_event_source_data_contract
          class_name: VirtualQueueDLRRedemptionLeaveQueueEventModel
          data_contract_version: 0.0.1
          key_path:
            - name: _type
              value: RedemptionLeaveQueueEvent
          router_database: *database
          router_schema: *schema
          router_table: REDEMPTION_LEAVE_QUEUE_EVENT
        - data_contract: app.src.data_structures.data_contracts.source.virtualqueue_dlr.v0.virtualqueue_dlr_redemption_redeem_boarding_group_position_event_source_data_contract
          class_name: VirtualQueueDLRRedemptionRedeemBoardingGroupPositionEventModel
          data_contract_version: 0.0.1
          key_path:
            - name: _type
              value: RedemptionRedeemBoardingGroupPositionEvent
          router_database: *database
          router_schema: *schema
          router_table: REDEMPTION_REDEEM_BOARDING_GROUP_POSITION_EVENT