stack_extension: &se dntm-teammembers
ingest_pattern: kinesis2kinesis
active: True
pattern_instances:
  - region: us-east-1
    resources:
      kinesis_dmz:
        retention_period: &kdr !!python/object/apply:app.src.reliability.Guest360YamlHandler.aws_cdk.aws_kinesis.days_retention
          - 30
        stream_mode: &ksm !!python/object/apply:aws_cdk.aws_kinesis.StreamMode
          - ON_DEMAND
      kinesis:
        retention_period: *kdr
        stream_mode: *ksm
      cross_account:
        cross_account_type: target
        cross_account_id: 536797260050
        cross_account_role_name: lllingest-use1-lod-lllingest-lambda
    data_pipe:
      default_router_database: DEFAULT_ROUTER_LOAD_LANDING # Needs update to appropriate default routing
      data_mapper_type: singleton
#      table_path: "Dinetime-teammembers"
      data_contracts:
        - data_contract: app.src.data_structures.data_contracts.source.dinetime.v0.dinetime_team_members_source_data_contract
          class_name: DineTimeTeamMembersModel
          data_contract_version: 0.0.1 
          router_database: LOAD_LANDING
          router_schema: LND_DINETIME
          router_table: TEAM_MEMBER
