stack_extension: &se titus-wdw
ingest_pattern: &ip kinesis2kinesis
active: True
pattern_instances:
  - region: us-east-1
    resources:
      kinesis:
        retention_period: &kdr !!python/object/apply:app.src.reliability.Guest360YamlHandler.aws_cdk.aws_kinesis.days_retention
          - 30
        stream_mode: &ksm !!python/object/apply:aws_cdk.aws_kinesis.StreamMode
          - ON_DEMAND
      kinesis_dmz:
        retention_period: &kdr_dmz !!python/object/apply:app.src.reliability.Guest360YamlHandler.aws_cdk.aws_kinesis.days_retention
          - 30
        stream_mode: &ksm_dmz !!python/object/apply:aws_cdk.aws_kinesis.StreamMode
          - ON_DEMAND
      cross_account:  # include this section if your kinesis stream is a non Guest-360 account
        cross_account_type: &cat target
        cross_account_id: &id 881472257814 # provide the target account where your source kinesis stream is
        cross_account_role_name: wdw-fastpass-S0001539-use1-lod-titus-iam_role  # Name of IAM role your cross-account lambda is using
    data_pipe:
      default_router_database: DEFAULT_ROUTER_LOAD_LANDING # Needs update to appropriate default routing
      default_schema: &schema LND_TITUS_WDW
#      data_contracts:
#        - data_contract: 
#          class_name: 
#          data_contract_version: 0.0.1
#          key_path:
#            - name: 
#              value: 
#          router_database: LOAD_LANDING
#          router_schema: *schema
#          router_table: 