from typing import Optional


class AttractionMetadataLookup:
    """Lookup class for attraction metadata.  For example, this class will implement a method that given an attraction ID, return an with name, etc."""

    @property
    def attractions(
        self,
    ):
        return self._attractions

    def __init__(
        self,
    ):
        # TODO - The hard coded dict is for initial iteration only.  It will be updated with the actual DB lookup once the source feed is active.
        self._attractions = [
            {
                "id": "19336036",
                "name": "Minnie's Wonderful Christmastime Fireworks at Mickey's Very Merry Christmas Party",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {"id": "16767276", "name": "Enchanted Tales with Belle", "park": "WDW", "facility_id": "80007944"},
            {
                "id": "19630230",
                "name": "Disney Enchantment - Now Through April 2, 2023",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {"id": "18904172", "name": "Alien Swirling Saucers", "park": "WDW", "facility_id": "80007998"},
            {"id": "80010149", "name": "it's a small world", "park": "WDW", "facility_id": "80007944"},
            {"id": "18375495", "name": "Frozen Ever After", "park": "WDW", "facility_id": "80007838"},
            {"id": "18715885", "name": "Fireworks & Nighttime Spectaculars", "park": "WDW", "facility_id": "80007944"},
            {"id": "80010114", "name": "Buzz Lightyear's Space Ranger Spin", "park": "WDW", "facility_id": "80007944"},
            {"id": "80010107", "name": "Astro Orbiter", "park": "WDW", "facility_id": "80007944"},
            {
                "id": "20021105",
                "name": "ZZ-Star Wars: Rise of the Resistance - Recover to Self, All Day",
                "park": "WDW",
                "facility_id": "80007998",
            },
            {
                "id": "20031202",
                "name": "ZZ-Remy's Ratatouille Adventure - Next Day, All Genie+",
                "park": "WDW",
                "facility_id": "80007838",
            },
            {
                "id": "18965501",
                "name": "UP! A Great Bird Adventure - Temporarily Unavailable",
                "park": "WDW",
                "facility_id": "80007823",
            },
            {"id": "19583373", "name": "Disney Junior Play and Dance!", "park": "WDW", "facility_id": "80007998"},
            {
                "id": "20011005",
                "name": "ZZ-Avatar Flight of Passage - Recover to Self, All Day",
                "park": "WDW",
                "facility_id": "80007823",
            },
            {
                "id": "202731",
                "name": "Disney Junior Dance Party! - Temporarily Unavailable",
                "park": "WDW",
                "facility_id": "80007998",
            },
            {"id": "18665186", "name": "Avatar Flight of Passage", "park": "WDW", "facility_id": "80007823"},
            {
                "id": "20021106",
                "name": "ZZ-Star Wars: Rise of the Resistance - Next Day, Self and Genie+",
                "park": "WDW",
                "facility_id": "80007998",
            },
            {"id": "411776692", "name": "Meet Mickey at Town Square Theater", "park": "WDW", "facility_id": "80007944"},
            {
                "id": "20021106",
                "name": "ZZ-Mickey & Minnie's Runaway Railway - Recover to Self, All Day",
                "park": "WDW",
                "facility_id": "80007998",
            },
            {"id": "80010218", "name": "The Twilight Zone Tower of Terror", "park": "WDW", "facility_id": "80007998"},
            {
                "id": "20041304",
                "name": "ZZ-Space Mountain - Next Day, All Genie+",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {
                "id": "20011001",
                "name": "ZZ-Avatar Flight of Passage - Recovery",
                "park": "WDW",
                "facility_id": "80007823",
            },
            {
                "id": "20011006",
                "name": "ZZ-Expedition Everest - Recover to Self, All Day",
                "park": "WDW",
                "facility_id": "80007823",
            },
            {
                "id": "61268",
                "name": "Holiday Wishes - Celebrate the Spirit of the Season",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {"id": "80010887", "name": "Fantasmic!", "park": "WDW", "facility_id": "80007998"},
            {
                "id": "8320000",
                "name": "Mickey’s Once Upon a Christmastime Parade During Disney Very Merriest After Hours",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {
                "id": "8320",
                "name": "Mickey’s Once Upon a Christmastime Parade",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {"id": "209857", "name": "Toy Story Mania!", "park": "WDW", "facility_id": "80007998"},
            {"id": "96", "name": "Mickey's Jammin' Jungle Parade", "park": "WDW", "facility_id": "80007823"},
            {"id": "19581372", "name": "Feathered Friends in Flight!  ", "park": "WDW", "facility_id": "80007823"},
            {
                "id": "20031206",
                "name": "ZZ-Frozen Ever After - Recover to Self, All Day",
                "park": "WDW",
                "facility_id": "80007838",
            },
            {
                "id": "20031201",
                "name": "ZZ-Remy's Ratatouille Adventure - Recovery",
                "park": "WDW",
                "facility_id": "80007838",
            },
            {
                "id": "20011004",
                "name": "ZZ-Expedition Everest - Next Day, All Genie+",
                "park": "WDW",
                "facility_id": "80007823",
            },
            {"id": "80010177", "name": "Pirates of the Caribbean", "park": "WDW", "facility_id": "80007944"},
            {"id": "80010228", "name": "TriceraTop Spin", "park": "WDW", "facility_id": "80007823"},
            {"id": "80010162", "name": "Mad Tea Party", "park": "WDW", "facility_id": "80007944"},
            {"id": "80010154", "name": "Kali River Rapids", "park": "WDW", "facility_id": "80007823"},
            {
                "id": "276291",
                "name": "Disneyâs Celebrate America! â A Fourth of July Concert in the Sky",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {
                "id": "20031204",
                "name": "ZZ-Frozen Ever After - Next Day, All Genie+",
                "park": "WDW",
                "facility_id": "80007838",
            },
            {"id": "20041303", "name": "ZZ-Space Mountain - Recovery", "park": "WDW", "facility_id": "80007944"},
            {"id": "12432", "name": "Festival of the Lion King", "park": "WDW", "facility_id": "80007823"},
            {
                "id": "16767263",
                "name": "Under the Sea - Journey of The Little Mermaid",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {"id": "80010848", "name": "Beauty & The Beast Live on Stage", "park": "WDW", "facility_id": "80007998"},
            {
                "id": "26068",
                "name": "Expedition Everest - Legend of the Forbidden Mountain",
                "park": "WDW",
                "facility_id": "80007823",
            },
            {"id": "18368385", "name": "Meet Olaf at Celebrity Spotlight", "park": "WDW", "facility_id": "80007998"},
            {"id": "80010191", "name": "Spaceship Earth", "park": "WDW", "facility_id": "80007838"},
            {"id": "80010150", "name": "It's Tough to be a Bug!", "park": "WDW", "facility_id": "80007823"},
            {
                "id": "321125",
                "name": "Move It! Shake It! MousekeDance It! Street Party - Temporarily Unavailable",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {"id": "19259335", "name": "Mickey & Minnie's Runaway Railway", "park": "WDW", "facility_id": "80007998"},
            {
                "id": "17506065",
                "name": "Character Greeting in Town Square Theater",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {"id": "16767284", "name": "Seven Dwarfs Mine Train", "park": "WDW", "facility_id": "80007944"},
            {"id": "80010170", "name": "Mickey's PhilharMagic", "park": "WDW", "facility_id": "80007944"},
            {"id": "80010129", "name": "Dumbo the Flying Elephant", "park": "WDW", "facility_id": "80007944"},
            {
                "id": "20021101",
                "name": "ZZ-Star Wars: Rise of the Resistance - Recovery",
                "park": "WDW",
                "facility_id": "80007998",
            },
            {"id": "80010222", "name": "Tomorrowland Speedway", "park": "WDW", "facility_id": "80007944"},
            {"id": "19263735", "name": "Millennium Falcon: Smugglers Run", "park": "WDW", "facility_id": "80007998"},
            {
                "id": "20011002",
                "name": "ZZ-Avatar Flight of Passage - Next Day, All Genie+",
                "park": "WDW",
                "facility_id": "80007823",
            },
            {
                "id": "20041301",
                "name": "ZZ-Seven Dwarfs Mine Train - Recovery",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {
                "id": "16665969",
                "name": "Sighting in Fantasyland near Princess Fairytale Hall",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {"id": "12248", "name": "Fantasy In The Sky Fireworks", "park": "WDW", "facility_id": "80007944"},
            {
                "id": "20031207",
                "name": "ZZ-Guardians of the Galaxy - Next Day, Self and Genie+",
                "park": "WDW",
                "facility_id": "80007838",
            },
            {
                "id": "80010896",
                "name": "Voyage of The Little Mermaid - Temporarily Unavailable",
                "park": "WDW",
                "facility_id": "80007998",
            },
            {"id": "80010110", "name": "Big Thunder Mountain Railroad", "park": "WDW", "facility_id": "80007944"},
            {
                "id": "80010182",
                "name": "Rock 'n' Roller Coaster Starring Aerosmith",
                "park": "WDW",
                "facility_id": "80007998",
            },
            {
                "id": "20031205",
                "name": "ZZ-Remy's Ratatouille Adventure - Recover to Self, All Day",
                "park": "WDW",
                "facility_id": "80007838",
            },
            {
                "id": "411854079",
                "name": "Minnie's Wonderful Christmastime Fireworks",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {"id": "80010208", "name": "Haunted Mansion", "park": "WDW", "facility_id": "80007944"},
            {
                "id": "19336036",
                "name": "Minnie's Wonderful Christmastime Fireworks During Disney Very Merriest After Hours",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {
                "id": "17505397",
                "name": "Meet Princess Tiana and a Visiting Princess at Princess Fairytale Hall",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {"id": "80010231", "name": "Walt Disney: One Man's Dream", "park": "WDW", "facility_id": "80007998"},
            {"id": "431484", "name": "A Totally Tomorrowland Christmas!", "park": "WDW", "facility_id": "80007944"},
            {
                "id": "18498503",
                "name": "Meet Cinderella and a Visiting Princess at Princess Fairytale Hall",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {"id": "20031203", "name": "ZZ-Frozen Ever After - Recovery", "park": "WDW", "facility_id": "80007838"},
            {"id": "136550", "name": "Monsters Inc. Laugh Floor", "park": "WDW", "facility_id": "80007944"},
            {
                "id": "161106",
                "name": "Finding Nemo - The Musical - Temporarily Unavailable",
                "park": "WDW",
                "facility_id": "80007823",
            },
            {"id": "19276204", "name": "Lightning McQueen's Racing Academy ", "park": "WDW", "facility_id": "80007998"},
            {
                "id": "411550125",
                "name": "Finding Nemo: The Big Blue... and Beyond! - Now Open!",
                "park": "WDW",
                "facility_id": "80007823",
            },
            {"id": "20194", "name": "Soarin' Around the World", "park": "WDW", "facility_id": "80007838"},
            {
                "id": "17421326",
                "name": "Meet Favorite Disney Pals at Adventurers Outpost",
                "park": "WDW",
                "facility_id": "80007823",
            },
            {
                "id": "411854078",
                "name": "Mickey's Once Upon a Christmastime Parade",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {"id": "15850196", "name": "Meet Mickey at Town Square Theater", "park": "WDW", "facility_id": "80007944"},
            {"id": "62992", "name": "Turtle Talk With Crush", "park": "WDW", "facility_id": "80007838"},
            {
                "id": "20031209",
                "name": "ZZ-Guardians of the Galaxy - Same Day, Self and Genie+",
                "park": "WDW",
                "facility_id": "80007838",
            },
            {"id": "19503896", "name": "Palais du Cinéma", "park": "WDW", "facility_id": "80007838"},
            {
                "id": "20031208",
                "name": "ZZ-Guardians of the Galaxy - Next Day, All Genie+",
                "park": "WDW",
                "facility_id": "80007838",
            },
            {
                "id": "20021102",
                "name": "ZZ-Star Wars: Rise of the Resistance - Next Day, All Genie+",
                "park": "WDW",
                "facility_id": "80007998",
            },
            {"id": "18665185", "name": "Na'vi River Journey", "park": "WDW", "facility_id": "80007823"},
            {"id": "19630156", "name": "Disney KiteTails", "park": "WDW", "facility_id": "80007823"},
            {
                "id": "20041305",
                "name": "ZZ-Seven Dwarfs Mine Train - Recover to Self, All Day",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {"id": "18679393", "name": "Pandora - The World of Avatar", "park": "WDW", "facility_id": "80007823"},
            {"id": "16491297", "name": "The Barnstormer", "park": "WDW", "facility_id": "80007944"},
            {"id": "18904138", "name": "Slinky Dog Dash", "park": "WDW", "facility_id": "80007998"},
            {"id": "80010233", "name": "Whac-A-Packycephalosaur", "park": "WDW", "facility_id": "80007823"},
            {
                "id": "20041302",
                "name": "ZZ-Seven Dwarfs Mine Train - Next Day, All Genie+",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {"id": "80010199", "name": "Test Track", "park": "WDW", "facility_id": "80007838"},
            {"id": "80010173", "name": "Mission: SPACE", "park": "WDW", "facility_id": "80007838"},
            {
                "id": "20021103",
                "name": "ZZ-Mickey & Minnie's Runaway Railway - Recovery",
                "park": "WDW",
                "facility_id": "80007998",
            },
            {"id": "80010151", "name": "Muppet*Vision 3D", "park": "WDW", "facility_id": "80007998"},
            {"id": "80010157", "name": "Kilimanjaro Safaris", "park": "WDW", "facility_id": "80007823"},
            {"id": "20011003", "name": "ZZ-Expedition Everest - Recovery", "park": "WDW", "facility_id": "80007823"},
            {
                "id": "20041306",
                "name": "ZZ-Space Mountain - Recover to Self, All Day",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {
                "id": "20021104",
                "name": "ZZ-Mickey & Minnie's Runaway Railway - Next Day, All Genie+",
                "park": "WDW",
                "facility_id": "80007998",
            },
            {"id": "17718925", "name": "Disney Festival of Fantasy Parade", "park": "WDW", "facility_id": "80007944"},
            {"id": "18397938", "name": "Frozen at Walt Disney World Resort", "park": "WDW", "facility_id": "80007838"},
            {"id": "80010117", "name": "Prince Charming Regal Carrousel", "park": "WDW", "facility_id": "80007944"},
            {
                "id": "411499845",
                "name": "Guardians of the Galaxy: Cosmic Rewind - New!",
                "park": "WDW",
                "facility_id": "80007838",
            },
            {
                "id": "17506065",
                "name": "Character Greeting in Town Square Theater",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {
                "id": "80010152",
                "name": "Journey Into Imagination With Figment",
                "park": "WDW",
                "facility_id": "80007838",
            },
            {"id": "80010166", "name": "Mammoth Marathon", "park": "WDW", "facility_id": "80007823"},
            {"id": "19134179", "name": "The Edge Effect", "park": "WDW", "facility_id": "80007944"},
            {"id": "80010123", "name": "DINOSAUR", "park": "WDW", "facility_id": "80007823"},
            {
                "id": "207395",
                "name": "Gran Fiesta Tour Starring The Three Caballeros",
                "park": "WDW",
                "facility_id": "80007838",
            },
            {
                "id": "80010224",
                "name": "Tomorrowland Transit Authority PeopleMover",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {
                "id": "18672598",
                "name": "Happily Ever After - Returning April 3, 2023!",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {
                "id": "80010213",
                "name": "The Many Adventures of Winnie the Pooh",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {
                "id": "8320",
                "name": "Mickey's Once Upon a Christmastime Parade at Mickey's Very Merry Christmas Party",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {"id": "107785", "name": "The Seas with Nemo & Friends", "park": "WDW", "facility_id": "80007838"},
            {
                "id": "19330300",
                "name": "The Animation Experience at Conservation Station",
                "park": "WDW",
                "facility_id": "80007823",
            },
            {
                "id": "18269694",
                "name": "Disney and Pixar Short Film Festival",
                "park": "WDW",
                "facility_id": "80007838",
            },
            {
                "id": "19577085",
                "name": "Disney's Hollywood Studios Entertainment",
                "park": "WDW",
                "facility_id": "80007998",
            },
            {
                "id": "17752793",
                "name": "Meet Tinker Bell at Town Square Theater - Temporarily Unavailable",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {"id": "80010210", "name": "The Magic Carpets of Aladdin", "park": "WDW", "facility_id": "80007944"},
            {"id": "19497835", "name": "Remy's Ratatouille Adventure", "park": "WDW", "facility_id": "80007838"},
            {
                "id": "18262680",
                "name": "Holiday Wishes - New Year's Celebration",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {"id": "80010176", "name": "Peter Pan's Flight", "park": "WDW", "facility_id": "80007944"},
            {"id": "80010190", "name": "Space Mountain", "park": "WDW", "facility_id": "80007944"},
            {
                "id": "17842841",
                "name": "For the First Time in Forever: A Frozen Sing-Along Celebration",
                "park": "WDW",
                "facility_id": "80007998",
            },
            {"id": "80010220", "name": "Tom Sawyer Island", "park": "WDW", "facility_id": "80007944"},
            {"id": "80010232", "name": "Walt Disney's Carousel of Progress", "park": "WDW", "facility_id": "80007944"},
            {
                "id": "80010193",
                "name": "Star Tours - The Adventures Continue",
                "park": "WDW",
                "facility_id": "80007998",
            },
            {"id": "136", "name": "Indiana Jones Epic Stunt Spectacular!", "park": "WDW", "facility_id": "80007998"},
            {"id": "19263736", "name": "Star Wars: Rise of the Resistance", "park": "WDW", "facility_id": "80007998"},
            {
                "id": "20021107",
                "name": "ZZ-Star Wars: Rise of the Resistance - Next Day, Self and Genie+",
                "park": "WDW",
                "facility_id": "80007998",
            },
            {
                "id": "18263038",
                "name": "Star Wars at Walt Disney World Resort",
                "park": "WDW",
                "facility_id": "80007998",
            },
            {
                "id": "18368386",
                "name": "Meet Disney Stars at Red Carpet Dreams",
                "park": "WDW",
                "facility_id": "80007998",
            },
            {"id": "80010161", "name": "Living with the Land", "park": "WDW", "facility_id": "80007838"},
            {"id": "80010153", "name": "Jungle Cruise", "park": "WDW", "facility_id": "80007944"},
            {"id": "16874126", "name": "Meet Ariel at Her Grotto", "park": "WDW", "facility_id": "80007944"},
            {"id": "80010192", "name": "Splash Mountain", "park": "WDW", "facility_id": "80007944"},
            {
                "id": "20041307",
                "name": "ZZ-TRON Lightcycle / Run - Next Day, All Genie+",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {
                "id": "20041308",
                "name": "ZZ-TRON Lightcycle / Run - Next Day, Self and Genie+",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {
                "id": "20041309",
                "name": "ZZ-TRON Lightcycle / Run - Same Day, Self and Genie+",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {
                "id": "411504498",
                "name": "TRON Lightcycle / Run - Soft Opening March 20 to April 2; Opening April 4",
                "park": "WDW",
                "facility_id": "80007944",
            },
            {"id": "10001002", "name": "ZZ-Dummy_Recovery_G1", "park": "DLR", "facility_id": "330339"},
            {"id": "10001003", "name": "ZZ-Dummy_Recovery_G2", "park": "DLR", "facility_id": "330339"},
            {"id": "10002001", "name": "ZZ-Dummy_Recovery_Rise", "park": "DLR", "facility_id": "330339"},
            {"id": "18237232", "name": "it's a small world Holiday", "park": "DLR", "facility_id": "330339"},
            {"id": "16203280", "name": "World of Color", "park": "DLR", "facility_id": "336894"},
            {"id": "18052105", "name": "Disneyland Forever ", "park": "DLR", "facility_id": "330339"},
            {
                "id": "353461",
                "name": "The Disneyland Story presenting Great Moments with Mr. Lincoln",
                "park": "DLR",
                "facility_id": "330339",
            },
            {
                "id": "353337",
                "name": "Gadget's Go Coaster - Temporarily Unavailable",
                "park": "DLR",
                "facility_id": "330339",
            },
            {
                "id": "353421",
                "name": "Roger Rabbit's Car Toon Spin - Temporarily Unavailable",
                "park": "DLR",
                "facility_id": "330339",
            },
            {
                "id": "353451",
                "name": "Guardians of the Galaxy - Mission: BREAKOUT!",
                "park": "DLR",
                "facility_id": "336894",
            },
            {"id": "353379", "name": "Pixar Pal-A-Round - Swinging", "park": "DLR", "facility_id": "336894"},
            {"id": "353439", "name": "Star Tours - The Adventures Continue", "park": "DLR", "facility_id": "330339"},
            {"id": "401483", "name": "Fantasmic! - Returning May 28, 2022", "park": "DLR", "facility_id": "330339"},
            {"id": "18343088", "name": "Luigi's Rollickin' Roadsters", "park": "DLR", "facility_id": "336894"},
            {"id": "16514431", "name": "Mater's Junkyard Jamboree", "park": "DLR", "facility_id": "336894"},
            {
                "id": "353387",
                "name": "Monsters, Inc. Mike & Sulley to the Rescue!",
                "park": "DLR",
                "facility_id": "336894",
            },
            {"id": "19285637", "name": "Inside Out Emotional Whirlwind", "park": "DLR", "facility_id": "336894"},
            {"id": "353367", "name": "Jessie's Critter Carousel", "park": "DLR", "facility_id": "336894"},
            {"id": "353361", "name": "Jumpin' Jellyfish", "park": "DLR", "facility_id": "336894"},
            {"id": "19193461", "name": "Star Wars: Rise of the Resistance", "park": "DLR", "facility_id": "330339"},
            {"id": "15757001", "name": "Swingtown", "park": "DLR", "facility_id": "330339"},
            {"id": "353303", "name": "Incredicoaster", "park": "DLR", "facility_id": "336894"},
            {"id": "353345", "name": "Grizzly River Run", "park": "DLR", "facility_id": "336894"},
            {"id": "353449", "name": "The Many Adventures of Winnie the Pooh", "park": "DLR", "facility_id": "330339"},
            {"id": "353325", "name": "Walt Disney's Enchanted Tiki Room", "park": "DLR", "facility_id": "330339"},
            {
                "id": "18771248",
                "name": "Frozen - Live at the Hyperion Dining Packages",
                "park": "DLR",
                "facility_id": "336894",
            },
            {"id": "15822029", "name": "Goofy's Sky School", "park": "DLR", "facility_id": "336894"},
            {"id": "353405", "name": "Pirates of the Caribbean", "park": "DLR", "facility_id": "330339"},
            {"id": "353365", "name": "King Arthur Carrousel", "park": "DLR", "facility_id": "330339"},
            {"id": "353369", "name": "Mad Tea Party", "park": "DLR", "facility_id": "330339"},
            {"id": "353375", "name": "Mark Twain Riverboat", "park": "DLR", "facility_id": "330339"},
            {"id": "18243993", "name": "Star Wars: Path of the Jedi", "park": "DLR", "facility_id": "330339"},
            {"id": "353399", "name": "Peter Pan's Flight", "park": "DLR", "facility_id": "330339"},
            {"id": "353401", "name": "Pinocchio's Daring Journey", "park": "DLR", "facility_id": "330339"},
            {"id": "353425", "name": "Sailing Ship Columbia", "park": "DLR", "facility_id": "330339"},
            {"id": "353429", "name": "Snow White's Enchanted Wish", "park": "DLR", "facility_id": "330339"},
            {
                "id": "353381",
                "name": "Mickey's House and Meet Mickey - Temporarily Unavailable",
                "park": "DLR",
                "facility_id": "330339",
            },
            {"id": "19193459", "name": "Millennium Falcon: Smugglers Run", "park": "DLR", "facility_id": "330339"},
            {"id": "353389", "name": "Mr. Toad's Wild Ride", "park": "DLR", "facility_id": "330339"},
            {"id": "353435", "name": "Space Mountain", "park": "DLR", "facility_id": "330339"},
            {"id": "353437", "name": "Splash Mountain", "park": "DLR", "facility_id": "330339"},
            {"id": "353377", "name": "Matterhorn Bobsleds", "park": "DLR", "facility_id": "330339"},
            {"id": "18708628", "name": "Disney Junior Dance Party!", "park": "DLR", "facility_id": "336894"},
            {"id": "3908469", "name": "A Christmas Fantasy Parade ", "park": "DLR", "facility_id": "330339"},
            {
                "id": "424945",
                "name": "Believe...In Holiday Magic Fireworks Spectacular ",
                "park": "DLR",
                "facility_id": "330339",
            },
            {"id": "18752875", "name": "Mater's Graveyard JamBOOree", "park": "DLR", "facility_id": "336894"},
            {"id": "18237368", "name": "Hyperspace Mountain", "park": "DLR", "facility_id": "330339"},
            {"id": "18848246", "name": "Luigi's Joy to the Whirl", "park": "DLR", "facility_id": "336894"},
            {"id": "18848247", "name": "Mater's Jingle Jamboree", "park": "DLR", "facility_id": "336894"},
            {
                "id": "17644533",
                "name": "New Year's Eve Fantasy in the Sky Fireworks Spectacular",
                "park": "DLR",
                "facility_id": "330339",
            },
            {"id": "19324604", "name": "Soarin' Over California", "park": "DLR", "facility_id": "336894"},
            {"id": "19259687", "name": "Mickey's Mix Magic with Fireworks", "park": "DLR", "facility_id": "330339"},
            {"id": "18847498", "name": "it's a small world Holiday Lighting ", "park": "DLR", "facility_id": "330339"},
            {"id": "10001001", "name": "ZZ-Dummy_Recovery_Genie+", "park": "DLR", "facility_id": "330339"},
            {"id": "10002002", "name": "ZZ-Dummy_Recovery_Web", "park": "DLR", "facility_id": "330339"},
            {"id": "3534570", "name": "Turtle Talk with Crush", "park": "DLR", "facility_id": "336894"},
            {"id": "19531124", "name": "WEB SLINGERS: A Spider-Man Adventure", "park": "DLR", "facility_id": "336894"},
            {"id": "16514416", "name": "Radiator Springs Racers", "park": "DLR", "facility_id": "336894"},
            {
                "id": "16581435",
                "name": "Red Car Trolley - Temporarily Unavailable",
                "park": "DLR",
                "facility_id": "336894",
            },
            {
                "id": "15575069",
                "name": "The Little Mermaid ~ Ariel's Undersea Adventure",
                "park": "DLR",
                "facility_id": "336894",
            },
            {"id": "353453", "name": "Toy Story Midway Mania!", "park": "DLR", "facility_id": "336894"},
            {"id": "15510732", "name": "Silly Symphony Swings", "park": "DLR", "facility_id": "336894"},
            {"id": "353431", "name": "Soarin' Around the World", "park": "DLR", "facility_id": "336894"},
            {"id": "18752877", "name": "Luigi's Honkin' Haul-O-Ween", "park": "DLR", "facility_id": "336894"},
            {"id": "18249927", "name": "Haunted Mansion Holiday", "park": "DLR", "facility_id": "330339"},
            {"id": "353457", "name": "Turtle Talk with Crush", "park": "DLR", "facility_id": "336894"},
            {
                "id": "15756384",
                "name": "Wintertime Enchantment at Sleeping Beauty's Winter Castle",
                "park": "DLR",
                "facility_id": "330339",
            },
            {"id": "353347", "name": "Haunted Mansion", "park": "DLR", "facility_id": "330339"},
            {"id": "353305", "name": "Casey Jr. Circus Train", "park": "DLR", "facility_id": "330339"},
            {"id": "353311", "name": "Davy Crockett's Explorer Canoes", "park": "DLR", "facility_id": "330339"},
            {"id": "367495", "name": "Alice in Wonderland", "park": "DLR", "facility_id": "330339"},
            {"id": "353291", "name": "Astro Orbitor", "park": "DLR", "facility_id": "330339"},
            {"id": "353293", "name": "Autopia", "park": "DLR", "facility_id": "330339"},
            {"id": "353295", "name": "Big Thunder Mountain Railroad", "park": "DLR", "facility_id": "330339"},
            {"id": "353301", "name": "Buzz Lightyear Astro Blasters", "park": "DLR", "facility_id": "330339"},
            {"id": "367492", "name": "it's a small world", "park": "DLR", "facility_id": "330339"},
            {"id": "353341", "name": "Golden Zephyr", "park": "DLR", "facility_id": "336894"},
            {"id": "353313", "name": "Disneyland Monorail", "park": "DLR", "facility_id": "330339"},
            {"id": "353315", "name": "Disneyland Railroad", "park": "DLR", "facility_id": "330339"},
            {"id": "353355", "name": "Indiana Jones Adventure", "park": "DLR", "facility_id": "330339"},
            {"id": "353363", "name": "Jungle Cruise", "park": "DLR", "facility_id": "330339"},
            {"id": "353323", "name": "Dumbo the Flying Elephant", "park": "DLR", "facility_id": "330339"},
            {"id": "353327", "name": "Finding Nemo Submarine Voyage", "park": "DLR", "facility_id": "330339"},
            {
                "id": "18774860",
                "name": "Guardians of the Galaxy - Monsters After Dark",
                "park": "DLR",
                "facility_id": "336894",
            },
            {"id": "353443", "name": "Storybook Land Canal Boats", "park": "DLR", "facility_id": "330339"},
            {"id": "353443", "name": "Storybook Land Canal Boats", "park": "DLR", "facility_id": "330339"},
            {
                "id": "19319963",
                "name": "Tale of the Lion King â Returning May 28, 2022",
                "park": "DLR",
                "facility_id": "330339",
            },
            {"id": "19299875", "name": "Mickey's PhilharMagic", "park": "DLR", "facility_id": "336894"},
            {"id": "18186543", "name": "Frozen - Live at the Hyperion", "park": "DLR", "facility_id": "336894"},
            {"id": "401479", "name": "World of Color", "park": "DLR", "facility_id": "336894"},
            {"id": "18516593", "name": "Main Street Electrical Parade ", "park": "DLR", "facility_id": "330339"},
            {
                "id": "18492231",
                "name": "World of Color - Season of Light - Temporarily Unavailable",
                "park": "DLR",
                "facility_id": "336894",
            },
            {"id": "18237232", "name": "it's a small world Holiday", "park": "DLR", "facility_id": "330339"},
            {"id": "18964141", "name": "Character Greetings near Pooh Corner", "park": "DLR", "facility_id": "330339"},
            {"id": "10002002", "name": "ZZ-Dummy_Recovery_Racers", "park": "DLR", "facility_id": "330339"},
            {"id": "10002003", "name": "ZZ-Dummy_Recovery_Web", "park": "DLR", "facility_id": "330339"},
        ]

    def get_attraction_by_id(
        self,
        attraction_id: str,
        facility_id: str,
    ) -> Optional[dict]:
        for attraction in self._attractions:
            if attraction["id"] == attraction_id and attraction["facility_id"] == facility_id:
                return attraction
