version: "3"

services:
  # Snowflake, DBT, GitHub Actions, and Docker
  analytics-engineering:
    container_name: helix-local-analytics-engineering-env-solo
    image: helix-local-analytics-engineering-env-solo
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../../:/workspace
    env_file:
      - ../../app/analytics_engineering/environment/secrets.env
    # this is for accessing docs from the container
    ports:
      - "127.0.0.1:8091:8080"
    stdin_open: true
    tty: true