with contracts_cte as (
    select *
    from (
            select data_contract_id as contract_id,
                data_contract_group_id as contract_group_id,
                'generic' as contract_type,
                data_version as contract_version,
                data_parent_version as contract_parent_version,
                data_status as contract_status,
                data_stage as contract_stage,
                data_valid_from as contract_valid_from,
                data_valid_to as contract_valid_to,
                data_sales_from as contract_sales_from,
                data_sales_to as contract_sales_to,
                data_entered_by as contract_entered_by,
                data_entered_on as contract_entered_on,
                data_modified_by as contract_modified_by,
                data_modified_on as contract_modified_on,
                data_nett_currency as contract_net_currency,
                data_rate_type as contract_rate_type,
                data_default_gross_currency as contract_default_gross_currency,
                data_prorata as contract_prorata,
                data_sell_alone as contract_sell_alone,
                data_pay_supplier_gross as contract_pay_supplier_gross,
                data_customer_pay_supplier as contract_customer_pay_supplier,
                data_errata_group as contract_errata_group,
                data_gen_product as contract_gen_product,
                data_starting_days as contract_starting_days,
                data_price_guaranteed as contract_price_guaranteed,
                data_country as contract_country,
                data_tourist_region as contract_tourist_region,
                data_city as contract_city,
                data_resort as contract_resort,
                data_stage_reason as contract_stage_reason,
                data_tax_exempt as contract_tax_exempt_indicator,
                data_tax_override as contract_tax_override,
                data_airport as contract_airport,
                data_duration_type as contract_duration_type,
                data_item_wise as contract_item_wise,
                data_term_and_condition as contract_terms_and_conditions,
                data_state as contract_state_value,
                data_accom_id as contract_accom_id,
                data_accom_code as contract_accom_code,
                data_accom_name as contract_accom_name,
                data_content_supplier_id as contract_content_supplier_id,
                data_content_supplier_code as contract_content_supplier_code,
                data_content_supplier_name as contract_content_supplier_name,
                data_send_documents_to_supplier as contract_send_documents_to_supplier,
                data_group_rates as contract_group_rates,
                data_date_wise_supplier as contract_date_wise_supplier,
                data_trackable as contract_trackable,
                data_voucher_code as contract_voucher_code,
                data_last_modified_timestamp as contract_last_modified_timestamp,
                data_special_pricing as contract_special_pricing,
                data_special_pricing_method as contract_special_pricing_method,
                data_pricing_override as contract_pricing_override,
                data_usage_override as contract_usage_override,
                data_bundle_product as contract_bundle_product,
                null as contract_eclc_allowed,
                null as contract_eclc_guranteed,
                null as contract_checkin_time,
                null as contract_checkout_time,
                null as contract_preferred_board_basis,
                null as contract_allocation_contract_id,
                null as contract_room_wise_or_pax_wise,
                null as contract_calculation_weight,
                null as contract_document_send_to_supplier,
                null as contract_rate_plan_code,
                null as contract_rate_plan_name,
                null as contract_deleted,
                null as contract_supplier_commission,
                null as contract_daily_weekly_rental,
                null as contract_one_way_free,
                null as contract_min_age,
                null as contract_max_age,
                null as contract_issue_voucher,
                null as contract_multi_hire,
                null as contract_one_way_fee_payable_locally,
                null as contract_daily_or_24hourly_rate,
                null as contract_max_duraiton,
                null as contract_periodic_factor,
                null as contract_calculation_type,
                null as contract_fc,
                null as contract_min_bank_to_deposit_days,
                null as contract_family_policy,
                null as contract_annual_policy,
                null as contract_commission,
                null as contract_policy_type,
                null as contract_max_price_allowed,
                null as contract_air_only,
                null as contract_unit_cost,
                null as contract_percentage,
                null as contract_winter_sports,
                null as contract_supplier_reference,
                null as contract_risk_number

			from {{ ref('sil__intermediate__travelbox__east__gen_contract_versioned') }}
            where metadata_version_end_datetime = '9999-12-31'
            union
            select data_contract_id as contract_id,
                data_contract_group_id as contract_group_id,
                'accommodation' as contract_type,
                data_version as contract_version,
                data_parent_version as contract_parent_version,
                data_status as contract_status,
                data_stage as contract_stage,
                data_valid_from as contract_valid_from,
                data_valid_to as contract_valid_to,
                data_sales_from as contract_sales_from,
                data_sales_to as contract_sales_to,
                data_entered_by as contract_entered_by,
                data_entered_on as contract_entered_on,
                data_modified_by as contract_modified_by,
                data_modified_on as contract_modified_on,
                data_nett_currency as contract_net_currency,
                data_rate_type as contract_rate_type,
                data_gross_default_currency as contract_default_gross_currency,
                data_prorata as contract_prorata,
                data_sell_alone as contract_sell_alone,
                data_pay_hotel_gross as contract_pay_supplier_gross,
                data_customer_pay_hotel as contract_customer_pay_supplier,
                data_errata_group as contract_errata_group,
                null as contract_gen_product,
                null as contract_starting_days,
                null as contract_price_guaranteed,
                null as contract_country,
                null as contract_tourist_region,
                null as contract_city,
                null as contract_resort,
                data_stage_reason as contract_stage_reason,
                data_tax_exempt as contract_tax_exempt_indicator,
                data_tax_override as contract_tax_override,
                null as contract_airport,
                null as contract_duration_type,
                null as contract_item_wise,
                null as contract_terms_and_conditions,
                null as contract_state_value,
                null as contract_accom_id,
                null as contract_accom_code,
                null as contract_accom_name,
                null as contract_content_supplier_id,
                null as contract_content_supplier_code,
                null as contract_content_supplier_name,
                null as contract_send_documents_to_supplier,
                data_group_rates as contract_group_rates,
                data_date_wise_supplier as contract_date_wise_supplier,
                data_trackable as contract_trackable,
                data_voucher_code as contract_voucher_code,
                data_last_modified_timestamp as contract_last_modified_timestamp,
                null as contract_special_pricing,
                null as contract_special_pricing_method,
                null as contract_pricing_override,
                null as contract_usage_override,
                null as contract_bundle_product,
                data_eclc_allowed as contract_eclc_allowed,
                data_eclc_guranteed as contract_eclc_guaranteed,
                data_checkin_time as contract_checkin_time,
                data_checkout_time as contract_checkout_time,
                data_preffered_board_basis as contract_preferred_board_basis,
                data_allocation_contract_id as contract_allocation_contract_id,
                data_room_wise_or_pax_wise as contract_room_wise_or_pax_wise,
                data_calculation_weight as contract_calculation_weight,
                data_document_send_to_accom as contract_document_send_to_supplier,
                data_rate_plan_code as contract_rate_plan_code,
                data_rate_plan_name as contract_rate_plan_name,
                data_deleted as contract_deleted,
                data_supp_comm as contract_supplier_commission,
                null as contract_daily_weekly_rental,
                null as contract_one_way_free,
                null as contract_min_age,
                null as contract_max_age,
                null as contract_issue_voucher,
                null as contract_multi_hire,
                null as contract_one_way_fee_payable_locally,
                null as contract_daily_or_24hourly_rate,
                null as contract_max_duration,
                null as contract_periodic_factor,
                null as contract_calculation_type,
                null as contract_fc,
                null as contract_min_bank_to_deposit_days,
                null as contract_family_policy,
                null as contract_annual_policy,
                null as contract_commission,
                null as contract_policy_type,
                null as contract_max_price_allowed,
                null as contract_air_only,
                null as contract_unit_cost,
                null as contract_percentage,
                null as contract_winter_sports,
                null as contract_supplier_reference,
                null as contract_risk_number

			from {{ ref('sil__intermediate__travelbox__east__acc_contract_versioned') }}
            where metadata_version_end_datetime = '9999-12-31'
            union
            select data_contract_id as contract_id,
                data_contract_group_id as contract_group_id,
                'car' as contract_type,
                data_version as contract_version,
                data_parent_version as contract_parent_version,
                data_status as contract_status,
                data_stage as contract_stage,
                data_valid_from as contract_valid_from,
                data_valid_to as contract_valid_to,
                data_sales_from as contract_sales_from,
                data_sales_to as contract_sales_to,
                data_entered_by as contract_entered_by,
                data_entered_on as contract_entered_on,
                data_modified_by as contract_modified_by,
                data_modified_on as contract_modified_on,
                data_nett_currency as contract_nett_currency,
                data_rate_type as contract_rate_type,
                data_default_gross_currency as contract_default_gross_currency,
                null as contract_prorata,
                null as contract_sell_alone,
                data_errata_group as contract_errata_group,
                null as contract_gen_product,
                null as contract_starting_days,
                null as contract_price_guaranteed,
                data_country as contract_country,
                null as contract_tourist_region,
                null as contract_city,
                null as contract_resort,
                null as contract_stage_reason,
                data_tax_excempt as contract_tax_exempt,
                data_tax_override as contract_tax_override,
                null as contract_airport,
                null as contract_duration_type,
                null as contract_item_wise,
                data_terms_conditions as contract_terms_and_conditions,
                null as contract_state_val,
                null as contract_accom_id,
                null as contract_accom_code,
                null as contract_accom_name,
                null as contract_content_supplier_id,
                null as contract_content_supplier_code,
                null as contract_content_supplier_name,
                null as contract_send_documents_to_supplier,
                null as contract_group_rates,
                null as contract_date_wise_supplier,
                data_trackable as contract_trackable,
                data_voucher_code as contract_voucher_code,
                null as contract_last_modified_timestamp,
                null as contract_special_pricing,
                null as contract_special_pricing_method,
                null as contract_pricing_override,
                null as contract_usage_override,
                null as contract_bundle_product,
                null as contract_eclc_allowed,
                null as contract_eclc_guranteed,
                null as contract_checkin_time,
                null as contract_checkout_time,
                null as contract_customer_pay_supplier,
                null as contract_pay_supplier_gross,
                null as contract_preffered_board_basis,
                null as contract_allocation_contract_id,
                null as contract_room_wise_or_pax_wise,
                null as contract_calculation_weight,
                null as contract_document_send_to_supplier,
                null as contract_rate_plan_code,
                null as contract_rate_plan_name,
                null as contract_deleted,
                null as contract_supplier_commission,
                data_daily_weekly_rental as contract_daily_weekly_rental,
                data_one_way_free as contract_one_way_free,
                data_min_age as contract_min_age,
                data_max_age as contract_max_age,
                data_issue_voucher as contract_issue_voucher,
                data_multi_hire as contract_multi_hire,
                data_one_way_fee_payable_locally as contract_one_way_fee_payable_locally,
                data_daily_or24_hourly_rate as contract_daily_or_24hourly_rate,
                data_max_duraiton as contract_max_duration,
                data_periodic_factor as contract_periodic_factor,
                data_calculation_type as contract_calculation_type,
                data_fc as contract_fc,
                data_min_bkg_to_dep_days as contract_min_bank_to_deposit_days,
                null as contract_family_policy,
                null as contract_annual_policy,
                null as contract_commission,
                null as contract_policy_type,
                null as contract_max_price_allowed,
                null as contract_air_only,
                null as contract_unit_cost,
                null as contract_percentage,
                null as contract_winter_sports,
                null as contract_supplier_reference,
                null as contract_risk_number

			from {{ ref('sil__intermediate__travelbox__east__car_contract_versioned') }}
            where metadata_version_end_datetime = '9999-12-31'
            union
            select data_contract_id as contract_id,
                data_contract_group as contract_group_id,
                'insurance' as contract_type,
                data_version as contract_version,
                data_parent_version as contract_parent_version,
                data_contract_status as contract_status,
                data_stage as contract_stage,
                data_valid_from as contract_valid_from,
                data_valid_to as contract_valid_to,
                data_sales_from as contract_sales_from,
                data_sales_to as contract_sales_to,
                data_entered_by as contract_entered_by,
                data_entered_on as contract_entered_on,
                data_modified_by as contract_modified_by,
                data_modified_on as contract_modified_on,
                data_net_currency as contract_net_currency,
                data_rate_type as contract_rate_type,
                data_gross_default_currency as contract_gross_default_currency,
                null as contract_prorata,
                null as contract_sell_alone,
                data_errata_group as contract_errata_group,
                null as contract_gen_product,
                null as contract_starting_days,
                null as contract_price_guaranteed,
                null as contract_country,
                null as contract_tourist_region,
                null as contract_city,
                null as contract_resort,
                data_stage_reason as contract_stage_reason,
                data_tax_excempt as contract_tax_exempt,
                data_tax_override as contract_tax_override,
                null as contract_airport,
                null as contract_duration_type,
                null as contract_item_wise,
                null as contract_terms_and_conditions,
                null as contract_state_val,
                null as contract_accom_id,
                null as contract_accom_code,
                null as contract_accom_name,
                null as contract_content_supplier_id,
                null as contract_content_supplier_code,
                null as contract_content_supplier_name,
                null as contract_send_documents_to_supplier,
                null as contract_group_rates,
                null as contract_date_wise_supplier,
                null as contract_trackable,
                data_voucher_code as contract_voucher_code,
                data_last_modified_timestamp as contract_last_modified_timestamp,
                null as contract_special_pricing,
                null as contract_special_pricing_method,
                null as contract_pricing_override,
                null as contract_usage_override,
                null as contract_bundle_product,
                null as contract_eclc_allowed,
                null as contract_eclc_guranteed,
                null as contract_checkin_time,
                null as contract_checkout_time,
                null as contract_customer_pay_supplier,
                null as contract_pay_supplier_gross,
                null as contract_preffered_board_basis,
                null as contract_allocation_contract_id,
                null as contract_room_wise_or_pax_wise,
                null as contract_calculation_weight,
                null as contract_document_send_to_supplier,
                null as contract_rate_plan_code,
                null as contract_rate_plan_name,
                null as contract_deleted,
                null as contract_supplier_commission,
                null as contract_daily_weekly_rental,
                null as contract_one_way_free,
                null as contract_min_age,
                null as contract_max_age,
                null as contract_issue_voucher,
                null as contract_multi_hire,
                null as contract_one_way_fee_payable_locally,
                null as contract_daily_or_24hourly_rate,
                null as contract_max_duration,
                null as contract_periodic_factor,
                null as contract_calculation_type,
                null as contract_fc,
                null as contract_min_bkg_to_dep_days,
                data_family_policy as contract_family_policy,
                data_annual_policy as contract_annual_policy,
                data_commission as contract_commission,
                data_policy_type as contract_policy_type,
                data_max_price_allowed as contract_max_price_allowed,
                data_air_only as contract_air_only,
                data_unit_cost as contract_unit_cost,
                data_percentage as contract_percentage,
                data_winter_sports as contract_winter_sports,
                data_supplier_ref as contract_supplier_reference,
                data_risk_no as contract_risk_number

			from {{ ref('sil__intermediate__travelbox__east__ins_contract_versioned') }}
            where metadata_version_end_datetime = '9999-12-31'
            union
            select data_contract_id as contract_id,
                data_contract_group_id as contract_group_id,
                'travel_service' as contract_type,
                data_version as contract_version,
                data_parent_version as contract_parent_version,
                data_status as contract_status,
                data_stage as contract_stage,
                data_valid_from as contract_valid_from,
                data_valid_to as contract_valid_to,
                data_sales_from as contract_sales_from,
                data_sales_to as contract_sales_to,
                data_entered_by as contract_entered_by,
                data_entered_on as contract_entered_on,
                data_modified_by as contract_modified_by,
                data_modified_on as contract_modified_on,
                data_nett_currency as contract_nett_currency,
                data_rate_type as contract_rate_type,
                data_gross_default_currency as contract_default_currency,
                null as contract_prorata,
                null as contract_sell_alone,
                null as contract_errata_group,
                null as contract_gen_product,
                null as contract_starting_days,
                null as contract_price_guaranteed,
                null as contract_country,
                null as contract_tourist_region,
                null as contract_city,
                null as contract_resort,
                data_stage_reason as contract_stage_reason,
                data_tax_exempt as contract_tax_exempt_indicator,
                data_tax_override as contract_tax_override,
                null as contract_airport,
                null as contract_duration_type,
                null as contract_item_wise,
                null as contract_terms_and_conditions,
                null as contract_state_val,
                null as contract_accom_id,
                null as contract_accom_code,
                null as contract_accom_name,
                null as contract_content_supplier_id,
                null as contract_content_supplier_code,
                null as contract_content_supplier_name,
                null as contract_send_documents_to_supplier,
                data_group_rates as contract_group_rates,
                data_date_wise_supplier as contract_date_wise_supplier,
                data_trackable as contract_trackable,
                data_voucher_code as contract_voucher_code,
                data_last_modified_timestamp as contract_last_modified_timestamp,
                null as contract_special_pricing,
                null as contract_special_pricing_method,
                null as contract_pricing_override,
                null as contract_usage_override,
                null as contract_bundle_product,
                null as contract_eclc_allowed,
                null as contract_eclc_guranteed,
                null as contract_checkin_time,
                null as contract_checkout_time,
                null as contract_customer_pay_supplier,
                null as contract_pay_supplier_gross,
                null as contract_preffered_board_basis,
                null as contract_allocation_contract_id,
                null as contract_room_wise_or_pax_wise,
                null as contract_calculation_weight,
                null as contract_document_send_to_supplier,
                null as contract_rate_plan_code,
                null as contract_rate_plan_name,
                null as contract_deleted,
                null as contract_supp_comm,
                null as contract_daily_weekly_rental,
                null as contract_one_way_free,
                null as contract_min_age,
                null as contract_max_age,
                null as contract_issue_voucher,
                null as contract_multi_hire,
                null as contract_one_way_fee_payable_locally,
                null as contract_daily_or_24hourly_rate,
                null as contract_max_duration,
                null as contract_periodic_factor,
                null as contract_calculation_type,
                null as contract_fc,
                null as contract_min_bkg_to_dep_days,
                null as contract_family_policy,
                null as contract_annual_policy,
                null as contract_commission,
                null as contract_policy_type,
                null as contract_max_price_allowed,
                null as contract_air_only,
                null as contract_unit_cost,
                null as contract_percentage,
                null as contract_winter_sports,
                null as contract_supplier_reference,
                null as contract_risk_number

			from {{ ref('sil__intermediate__travelbox__east__trs_contract_versioned') }}
            where metadata_version_end_datetime = '9999-12-31'
        )
),

c_group_cte as (
    select *

	from {{ ref('sil__intermediate__travelbox__east__contract_group_versioned') }}
    where metadata_version_end_datetime = '9999-12-31'
),
c_company_cte as (
    select *

	from {{ ref('sil__intermediate__travelbox__east__cmp_company_versioned') }}
    where metadata_version_end_datetime = '9999-12-31'
),
c_division_cte as (
    select *

	from {{ ref('sil__intermediate__travelbox__east__cmp_division_versioned') }}
    where metadata_version_end_datetime = '9999-12-31'
),
pt_supplier_cte as (
    select *

	from {{ ref('sil__intermediate__travelbox__east__supplier_versioned') }}
    where metadata_version_end_datetime = '9999-12-31'
),
c_status_cte as (
    select *

	from {{ ref('sil__intermediate__travelbox__east__status_cleansed') }}
),
final_cte as (

    select c_group.data_supplier_id as contract_group_supplier_id,
    c_group.data_reference as contract_group_reference,
    c_group.data_description as contract_group_description,
    c_group.data_company as contract_group_company,
    c_group.data_division as contract_group_division,
    c_group.data_product as contract_group_product,
    c_group.data_addon as contract_group_addon,
    c_group.data_addon_priority as contract_group_addon_priority,
    c_group.data_pre_departure as contract_group_pre_departure,
    c_group.data_last_modified_time as contract_group_last_modified_time,
    c_group.data_contract_source as contract_group_contract_source,
    c_group.data_destination as contract_group_destination,
    c_company.data_name as company_name,
    c_division.data_name as division_name,
    pt_supplier.data_code as supplier_code,
    pt_supplier.data_identity as supplier_identity_value,
    pt_supplier.data_name as supplier_name,
    pt_supplier.data_address as supplier_address,
    pt_supplier.data_city as supplier_city,
    pt_supplier.data_resort as supplier_resort,
    pt_supplier.data_tourist_region as supplier_tourist_region,
    pt_supplier.data_post_code as supplier_post_code,
    contracts_cte.contract_id as contract_id,
    contracts_cte.contract_group_id as contract_group_id,
    contracts_cte.contract_type as contract_type,
    contracts_cte.contract_version as contract_version,
    contracts_cte.contract_parent_version as contract_parent_version,
    contracts_cte.contract_status as contract_status,
    c_status.data_name as contract_status_name,
    contracts_cte.contract_stage as contract_stage,
    contracts_cte.contract_valid_from as contract_valid_from,
    contracts_cte.contract_valid_to as contract_valid_to,
    contracts_cte.contract_sales_from as contract_sales_from,
    contracts_cte.contract_sales_to as contract_sales_to,
    contracts_cte.contract_entered_by as contract_entered_by,
    contracts_cte.contract_entered_on as contract_entered_on,
    contracts_cte.contract_modified_by as contract_modified_by,
    contracts_cte.contract_modified_on as contract_modified_on,
    contracts_cte.contract_net_currency as contract_net_currency,
    contracts_cte.contract_rate_type as contract_rate_type,
    contracts_cte.contract_default_gross_currency as contract_default_gross_currency,
    contracts_cte.contract_prorata as contract_prorata,
    contracts_cte.contract_sell_alone as contract_sell_alone,
    contracts_cte.contract_pay_supplier_gross as contract_pay_supplier_gross,
    contracts_cte.contract_errata_group as contract_errata_group,
    contracts_cte.contract_country as contract_country,
    contracts_cte.contract_stage_reason as contract_stage_reason,
    case
        when contracts_cte.contract_tax_exempt_indicator = '0' then 'n'
        when contracts_cte.contract_tax_exempt_indicator = '1' then 'y'
        else 'u'
    end as contract_tax_exempt_indicator,
    case
        when contracts_cte.contract_tax_override = '0' then 'n'
        when contracts_cte.contract_tax_override = '1' then 'y'
        else 'u'
    end as contract_tax_override,
    contracts_cte.contract_item_wise as contract_item_wise,
    contracts_cte.contract_terms_and_conditions as contract_terms_and_conditions,
    contracts_cte.contract_group_rates as contract_group_rates,
    contracts_cte.contract_date_wise_supplier as contract_date_wise_supplier,
    contracts_cte.contract_trackable as contract_trackable,
    contracts_cte.contract_voucher_code as contract_voucher_code,
    contracts_cte.contract_last_modified_timestamp as contract_last_modified_timestamp,
    contracts_cte.contract_gen_product as generic_contract_product,
    contracts_cte.contract_starting_days as generic_contract_starting_days,
    contracts_cte.contract_price_guaranteed as generic_contract_price_guaranteed,
    contracts_cte.contract_customer_pay_supplier as generic_contract_customer_pay_supplier,
    contracts_cte.contract_tourist_region as generic_contract_tourist_region,
    contracts_cte.contract_city as generic_contract_city,
    contracts_cte.contract_resort as generic_contract_resort,
    contracts_cte.contract_airport as generic_contract_airport,
    contracts_cte.contract_duration_type as generic_contract_duration_type,
    contracts_cte.contract_state_value as generic_contract_state_value,
    contracts_cte.contract_accom_id as generic_contract_accom_id,
    contracts_cte.contract_accom_code as generic_contract_accom_code,
    contracts_cte.contract_accom_name as generic_contract_accom_name,
    contracts_cte.contract_content_supplier_id as generic_contract_content_supplier_id,
    contracts_cte.contract_content_supplier_code as generic_contract_content_supplier_code,
    contracts_cte.contract_content_supplier_name as generic_contract_content_supplier_name,
    contracts_cte.contract_send_documents_to_supplier as generic_contract_send_documents_to_supplier,
    contracts_cte.contract_special_pricing as generic_contract_special_pricing,
    contracts_cte.contract_special_pricing_method as generic_contract_special_pricing_method,
    contracts_cte.contract_pricing_override as generic_contract_pricing_override,
    contracts_cte.contract_usage_override as generic_contract_usage_override,
    contracts_cte.contract_bundle_product as generic_contract_bundle_product,
    contracts_cte.contract_eclc_allowed as accommodation_contract_eclc_allowed,
    contracts_cte.contract_eclc_guranteed as accommodation_contract_eclc_guranteed,
    contracts_cte.contract_checkin_time as accommodation_contract_checkin_time,
    contracts_cte.contract_checkout_time as accommodation_contract_checkout_time,
    contracts_cte.contract_customer_pay_supplier as accommodation_contract_customer_pay_supplier,
    contracts_cte.contract_pay_supplier_gross as accommodation_contract_pay_supplier_gross,
    contracts_cte.contract_preferred_board_basis as accommodation_contract_preferred_board_basis,
    contracts_cte.contract_allocation_contract_id as accommodation_contract_allocation_contract_id,
    contracts_cte.contract_room_wise_or_pax_wise as accommodation_contract_room_wise_or_pax_wise,
    contracts_cte.contract_calculation_weight as accommodation_contract_calculation_weight,
    contracts_cte.contract_document_send_to_supplier as accommodation_contract_document_send_to_supplier,
    contracts_cte.contract_rate_plan_code as accommodation_contract_rate_plan_code,
    contracts_cte.contract_rate_plan_name as accommodation_contract_rate_plan_name,
    contracts_cte.contract_deleted as accommodation_contract_deleted,
    contracts_cte.contract_supplier_commission as accommodation_contract_supplier_commission,
    contracts_cte.contract_daily_weekly_rental as car_contract_daily_weekly_rental,
    contracts_cte.contract_one_way_free as car_contract_one_way_free,
    contracts_cte.contract_min_age as car_contract_min_age,
    contracts_cte.contract_max_age as car_contract_max_age,
    contracts_cte.contract_issue_voucher as car_contract_issue_voucher,
    contracts_cte.contract_multi_hire as car_contract_multi_hire,
    contracts_cte.contract_one_way_fee_payable_locally as car_contract_one_way_fee_payable_locally,
    contracts_cte.contract_daily_or_24hourly_rate as car_contract_daily_or_24hourly_rate,
    contracts_cte.contract_max_duraiton as car_contract_max_duration,
    contracts_cte.contract_periodic_factor as car_contract_periodic_factor,
    contracts_cte.contract_calculation_type as car_contract_calculation_type,
    contracts_cte.contract_fc as car_contract_fc,
    contracts_cte.contract_min_bank_to_deposit_days as contract_min_bank_to_deposit_days,
    contracts_cte.contract_family_policy as insurance_contract_family_policy,
    contracts_cte.contract_annual_policy as insurance_contract_annual_policy,
    contracts_cte.contract_commission as insurance_contract_commission,
    contracts_cte.contract_policy_type as insurance_contract_policy_type,
    contracts_cte.contract_max_price_allowed as insurance_contract_max_price_allowed,
    contracts_cte.contract_air_only as insurance_contract_air_only,
    contracts_cte.contract_unit_cost as insurance_contract_unit_cost,
    contracts_cte.contract_percentage as insurance_contract_percentage,
    contracts_cte.contract_winter_sports as insurance_contract_winter_sports,
    contracts_cte.contract_supplier_reference as insurance_contract_supplier_reference,
    contracts_cte.contract_risk_number as insurance_contract_risk_no
from contracts_cte
    inner join c_group_cte c_group on c_group.data_group_id = contracts_cte.contract_group_id
    and c_group.metadata_version_end_datetime = '9999-12-31'
    left join c_company_cte c_company on c_company.data_code = c_group.data_company
    and c_company.metadata_version_end_datetime = '9999-12-31'
    left join c_division_cte c_division on c_division.data_code = c_group.data_division
    and c_division.metadata_version_end_datetime = '9999-12-31'
    left join pt_supplier_cte pt_supplier on pt_supplier.data_supplier_id
    and pt_supplier.metadata_version_end_datetime = '9999-12-31'
    left join c_status_cte c_status on c_status.data_status_id = contracts_cte.contract_status

	)
select
    *
from
    final_cte