stack_extension: &se dinetime
ingest_pattern: &ip kinesis2kinesis
active: True
pattern_instances:
  - region: us-east-1
    resources:
      kinesis_dmz:
        retention_period: &kdr !!python/object/apply:app.src.reliability.Guest360YamlHandler.aws_cdk.aws_kinesis.days_retention
          - 30
        stream_mode: &ksm !!python/object/apply:aws_cdk.aws_kinesis.StreamMode
          - ON_DEMAND
      kinesis:
        retention_period: *kdr
        stream_mode: *ksm
      cross_account:  # include this section if your kinesis stream is a non Guest-360 account
        cross_account_type: &cat target
        cross_account_id: &id 830296027592 # provide the target account where your source kinesis stream is
        cross_account_role_name: WDPR-IA_DEVELOPER  # Name of IAM role your cross-account lambda is using
    data_pipe:
      default_router_database: DEFAULT_ROUTER_PROD_LANDING # Needs update to appropriate default routing
#      data_contracts:
#        - data_contract: 
#          class_name: 
#          data_contract_version: 0.0.1
#          key_path:
#            - name: 
#              value: 
#          router_database: PROD_LANDING
#          router_schema: LND_DINETIME
#          router_table: 