"""Source Data Contract Template for PHN_CHRG.json"""


from __future__ import annotations
from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field
from app.src.data_structures.data_contracts.source.dreams.global_dreams_source_data_contract import GlobalDreamsMetadata


class Data(BaseModel):
    """data for PHN_CHRG"""

    phn_chrg_id: int = Field(
        ...,
        alias="PHN_CHRG_ID",
        name="",
        description="",
        example=3408490982,
        guest_identifier=False,
        transaction_identifier=False,
        identifier_tag="",
    )
    phn_chrg_cl_dt: datetime = Field(
        ...,
        alias="PHN_CHRG_CL_DT",
        name="",
        description="",
        example="2023-06-10T03:50:00Z",
        guest_identifier=False,
        transaction_identifier=False,
        identifier_tag="",
    )
    phn_sys_rec_dt: datetime = Field(
        ...,
        alias="PHN_SYS_REC_DT",
        name="",
        description="",
        example="2023-06-11T03:50:00Z",
        guest_identifier=False,
        transaction_identifier=False,
        identifier_tag="",
    )
    phn_sys_rec_tm: datetime = Field(
        ...,
        alias="PHN_SYS_REC_TM",
        name="",
        description="",
        example="1970-01-01T03:52:27Z",
        guest_identifier=False,
        transaction_identifier=False,
        identifier_tag="",
    )
    phn_cl_term_pt_cty_nm: str = Field(
        ...,
        alias="PHN_CL_TERM_PT_CTY_NM",
        name="",
        description="",
        example="HARVESTER",
        guest_identifier=False,
        transaction_identifier=False,
        identifier_tag="",
    )
    phn_chrg_cl_tm: Optional[datetime] = Field(
        None,
        alias="PHN_CHRG_CL_TM",
        name="",
        description="",
        example="1970-01-01T03:50:00Z",
        guest_identifier=False,
        transaction_identifier=False,
        identifier_tag="",
    )
    phn_cl_typ_nm: str = Field(
        ...,
        alias="PHN_CL_TYP_NM",
        name="",
        description="",
        example="LD",
        guest_identifier=False,
        transaction_identifier=False,
        identifier_tag="",
    )
    phn_nb: str = Field(
        ...,
        alias="PHN_NB",
        name="",
        description="",
        example="16367228881",
        guest_identifier=False,
        transaction_identifier=False,
        identifier_tag="",
    )
    phn_cl_sec_cn: int = Field(
        ...,
        alias="PHN_CL_SEC_CN",
        name="",
        description="",
        example=100,
        guest_identifier=False,
        transaction_identifier=False,
        identifier_tag="",
    )
    create_usr_id_cd: str = Field(
        ...,
        alias="CREATE_USR_ID_CD",
        name="",
        description="",
        example="JAZZ",
        guest_identifier=False,
        transaction_identifier=False,
        identifier_tag="",
    )
    create_dts: datetime = Field(
        ...,
        alias="CREATE_DTS",
        name="",
        description="",
        example="2023-06-12T03:50:00Z",
        guest_identifier=False,
        transaction_identifier=False,
        identifier_tag="",
    )
    updt_usr_id_cd: str = Field(
        ...,
        alias="UPDT_USR_ID_CD",
        name="",
        description="",
        example="JAZZ",
        guest_identifier=False,
        transaction_identifier=False,
        identifier_tag="",
    )
    updt_dts: datetime = Field(
        ...,
        alias="UPDT_DTS",
        name="",
        description="",
        example="2023-06-13T03:50:00Z",
        guest_identifier=False,
        transaction_identifier=False,
        identifier_tag="",
    )
    jdo_seq_nb: int = Field(
        ...,
        alias="JDO_SEQ_NB",
        name="",
        description="",
        example=0,
        guest_identifier=False,
        transaction_identifier=False,
        identifier_tag="",
    )
    prge_dts: Optional[datetime] = Field(
        None,
        alias="PRGE_DTS",
        name="",
        description="",
        example="2023-07-18T06:30:37.488000Z",
        guest_identifier=False,
        transaction_identifier=False,
        identifier_tag="",
    )


class DREAMSFolioPhnChrgModel(BaseModel):
    """Payload class for DREAMSFolioPhnChrgModel"""

    class Config:
        """Payload Level Metadata"""

        title = "Phone Charge"
        stream_name = ""
        description = "This table holds the Phone Charges that are generated by Guests making phone calls from their hotel rooms."  # optional
        unique_identifier = ["data.PHN_CHRG_ID"]
        timezone = "UTC"  # optional
        pi_category = [""]  # optional
        isps = "Confidential"  # optional
        financial_data = True  # optional
        version = "0.0.1"
        key_path_name = "metadata.table-name"
        key_path_value = "PHN_CHRG"

    data: Data = Field(..., alias="data")
    metadata: GlobalDreamsMetadata = Field(..., alias="metadata")
