version: 2

models:
  - name: sil__guest_experience__magic_band__magic_band_configuration_current
    description: "{{ doc('sil__guest_experience__magic_band__magic_band_configuration_current') }}"

    config:
      tags:
        - layer=silver_final
        - domain=guest_experience
        - sub_domain=magic_band
        - active=LATEST
        - active=STAGE
        - active=LOAD
        - active=PROD

    columns:
      - name: configuration_id
        description: ""

      - name: product_id
        description: ""

      - name: product_type_id
        description: ""

      - name: type_code
        description: ""

      - name: type_description
        description: ""

      - name: top_color_id
        description: ""

      - name: top_color_code
        description: ""

      - name: top_color_name
        description: ""

      - name: bottom_color_id
        description: ""

      - name: bottom_color_code
        description: ""

      - name: bottom_color_name
        description: ""

      - name: manufacture_tool_id
        description: ""

      - name: manufacture_tool_code
        description: ""

      - name: manufacture_tool_description
        description: ""

      - name: module_configuration_id
        description: ""

      - name: module_id
        description: ""

      - name: module_code
        description: ""

      - name: module_description
        description: ""

      - name: module_version_id
        description: ""

      - name: module_version_code
        description: ""

      - name: module_version_description
        description: ""

      - name: vendor_id
        description: ""

      - name: vendor_code
        description: ""

      - name: vendor_name
        description: ""

      - name: sap_id
        description: ""

      - name: configuration_description
        description: ""

      - name: available_to_guest_indicator
        description: ""

      - name: configuration_confirmed_indicator
        description: ""

      - name: source_system_create_user_id
        description: ""

      - name: source_system_create_datetime
        description: ""

      - name: source_system_update_user_id
        description: ""

      - name: source_system_update_datetime
        description: ""

      - name: source_system_logical_delete_indicator
        description: ""
