version: 2

models:
  - name: sil__guest_experience__magic_band__magic_band_module_configuration_current
    description: "{{ doc('sil__guest_experience__magic_band__magic_band_module_configuration_current') }}"

    config:
      tags:
        - layer=silver_final
        - domain=guest_experience
        - sub_domain=magic_band
        - active=LATEST
        - active=STAGE
        - active=LOAD
        - active=PROD

    columns:
      - name: module_configuration_id
        description: ""

      - name: module_id
        description: ""

      - name: module_code
        description: ""

      - name: module_description
        description: ""

      - name: module_available_to_guest_indicator
        description: ""

      - name: module_version_id
        description: ""

      - name: module_version_code
        description: ""

      - name: module_version_description
        description: ""

      - name: module_version_available_to_guest_indicator
        description: ""

      - name: source_system_create_user_id
        description: ""

      - name: source_system_create_datetime
        description: ""

      - name: source_system_update_user_id
        description: ""

      - name: source_system_update_datetime
        description: ""

      - name: source_system_logical_delete_indicator
        description: ""
