stack_extension: &se shopdisney
ingest_pattern: &ip messaging
# *********
# CAUTION - ShopDisney only has one lower environment that Helix Latest/Stage/Load config files are all pointing to.
# Ensure that only 1 Helix Lower Environment is set Active=TRUE at any give time
active: True
# *********
pattern_instances:
  - region: &region-1 us-east-1
    resources:
      cluster_name: &rcm shopdisney
      kinesis: &kinesis
        stream_name: &stream_name shopdisney-kinesis
      ecs:
        ecr:
          repository_name: guest360/ingestion/google_pubsub_consumer
        secret_name: &secret_name lst-use1-shopdisney-secret # pragma: allowlist secret
        s3:
          bucket_name: *rcm
        services:
          - service_name: SHOPDISNEY-PUBSUB-ORDERS-QUEUE
            image_tag: &image v0.1.x
            desired_count : 1
            cloudmap: False
            environment: &environment
              DEFAULT_BATCH_SIZE : 400                                # Integer value gather than 0  Required: No  Default Value =  400
              DEFAULT_MAX_RETRY_ATTEMPT : 3                           # Integer value gather than 0  Required: No  Default Value =  3
              DEFAULT_RETRY_BATCH_SIZE :  5                           # Integer value gather than 0  Required: No  Default Value =  5
              DEFAULT_MAX_WAIT_MILLISECS : 100                        # Integer value gather than 0  Required: No  Default Value =  1000
              MAX_BATCH_SIZE : 500                                    # This is batch size limit from Kinesis. # Integer value gather than 0  Required: No  Default Value =  500
              MAX_WAIT_MILLISECS : 300                                # This is batch size limit from Kinesis. # Integer value gather than 0  Required: No  Default Value =  500
              LOGLEVEL : INFO                                         # Required: No  , Default Value = INFO  Python logging package severity level. [DEBUG, INFO, WARNING, ERROR,
              ENVIRONMENT :  latest                                   # Required: Yes , Default Value = “” ,Environment value (latest,stage,prod)
              REGION : *region-1                                      # Required: No  , Default Value = us-east-1     , AWS region
              KINESIS_STREAM :  *stream_name                          # Required: Yes , Default Value = “”, Kinesis stream name
              KINESIS_PARTITIONS : 10000                              # Required: No  , Default Value =  10000 , Number of distinct unique partition keys generated when sending da
              FAILED_MSG_BUCKET_NAME : *rcm                   # Required: Yes , S3 bucket name to store records after exhausting max retry attempt
              FAILED_MSG_BUCKET_PATH : /shopdisney-orders/ # TODO - do we want a different name?
              MAX_RETRY_ATTEMPT :   3                                 # Required: Yes , Default Value =  3  Number of attempts to send record to kinesis before writing to failed r
              GOOGLE_APPLICATION_CREDENTIALS :  *secret_name          # Required: Yes , parameter expected by PubSub library
              PUB_SUB_PROJECT :   dpr-rapi-us-qa-1               # Required: Yes , parameter expected by PubSub library
              PUB_SUB_SUBSCRIPTION : SFCC-ORDER-TRANSFER-G360  # https://mywiki.disney.com/display/RISE/Order+Service+Sequence+Diagrams
          - service_name: SHOPDISNEY-PUBSUB-PRODUCT-CATALOG-QUEUE
            image_tag: *image
            desired_count: 1
            cloudmap: False
            environment:
              <<: *environment
              FAILED_MSG_BUCKET_PATH : /shopdisney-product-catalog/ # TODO - do we want a different name?
              PUB_SUB_SUBSCRIPTION : CATALOG-IN-IP-DS-PRODUCTS-G360 # https://mywiki.disney.com/display/RISE/Catalog+Services+Sequence+Diagrams#CatalogServicesSequenceDiagrams-CATALOG-IN-IP-DS-PRODUCTS
    data_pipe:
      default_router_database: DEFAULT_ROUTER_LATEST_LANDING # Needs update to appropriate default routing
      default_schema: &schema LND_SHOPDISNEY
      data_mapper_type: nested-xml
#      table_path: # This value should match the "name" value under "key_path"
#      data_contracts: # This section needs to be updated for all data contracts for the source
#        - data_contract:
#          class_name:
#          data_contract_version: 0.0.1
#          key_path:
#            - name:
#              value:
#          router_database: &database LATEST_LANDING
#          router_schema: &schema LND_SHOPDISNEY
#          router_table: