---
name: Workflow Testing
on:
  workflow_dispatch:
  pull_request:

jobs:
  show-env:
    runs-on: [ "codebuild-ander134-test-${{ github.run_id }}-${{ github.run_attempt }}" ]
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install -g aws-cdk@2
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Synth
        shell: bash
        run: |
          cd iam_role
          npm install
          cdk synth 2>&1 | tee -a $GITHUB_STEP_SUMMARY

      - run: docker ps