---
name: Workflow Testing
on:
  workflow_dispatch:
    inputs:
      test_value_one:
        description: "Test Value 1"
        required: false
        type: string
      test_value_two:
        description: "Test Value 2"
        required: false
        type: string

jobs:
  show-env:
    runs-on: [ "ubuntu-latest" ]
    steps:
      - name: Test Step
        run: |
          # This exists as a placeholder for anyone who wants to test action code
          # before moving it into a pipeline flow.
          # When modifying this action, please return it to this state before merging your branch.