name: rebase pull requests

permissions:
  contents: write
  pull-requests: write

on:
  push:
  repository_dispatch:
    types: [rebase-pull-requests]
  workflow_dispatch: # for manual testing

jobs:
  auto-rebase:
    name: rebase dependabot PRs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 5
    steps:
      - name: rebase
        uses: 'bbeesley/gha-auto-dependabot-rebase@v1.3.151'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          task: recreate
